### ISSUE TITLE
Allow for conditional creation of RDS Aurora resources

### ISSUE THREAD

**Issue by shanedroid** [terraform-aws-modules/terraform-aws-rds-aurora#108]
Allow conditional creation of RDS Aurora resources similar to how [terraform-aws-vpc module handles uses `create_vpc`](https://github.com/terraform-aws-modules/terraform-aws-vpc#conditional-creation).

This is for a personal use case where we have many isolated smaller state files in use and sometimes do not wish for a specific Aurora cluster to be created/in use yet would want a workspace defined and valid TF state to exist (containing no Aurora resources).

**Comment by franviera92** [comment]
Yes is necessary, please

**Comment by icalvete** [comment]
+1 please

**Comment by antonbabenko** [comment]
Fixed in #159 and [v2.29.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.29.0) has been just released.
