### ISSUE TITLE
Cannot pass in security group from other module to allowed_security_groups

### ISSUE THREAD

**Issue by alex-gottschalk-roostify** [terraform-aws-modules/terraform-aws-rds-aurora#11]
When setting up a cluster resource like so...

    module "database" {
        source = "../modules/terraform-aws-modules/rds-aurora/aws"
        [...]
        allowed_security_groups = ["${module.asg_resources.asg_security_group_id}"]
        [...]
    }

I get this well-known terraform error:
`* module.database.aws_security_group_rule.default_ingress: aws_security_group_rule.default_ingress: value of 'count' cannot be computed`

This is despite the fact that `module.asg_resources.asg_security_group_id` is a string and not a list.

**Comment by max-rocket-internet** [comment]
I think you can solve this by just ensuring that the resource `module.asg_resources.asg_security_group_id` is created first, then the aurora stuff. i.e. run `terraform apply -target=module.asg_resources.asg_security_group_id` first.

Does that work?

**Comment by bugok** [comment]
Just hit that as well.

**Comment by antonbabenko** [comment]
Resolved in [v1.8.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v1.8.0) by @dekimsey
