### ISSUE TITLE
Add permissions boundary aws iam role

### ISSUE THREAD

**Issue by edersonbrilhante** [terraform-aws-modules/terraform-aws-rds-aurora#115]
In my case, my AWS account I am using permissions boundary to avoid creating a new role with bigger permissions. So any new role must set these permissions.
To run the resource aws_iam_role. rds_enhanced_monitoring, it is needed to set these permissions boundary.
Example:
```
resource "aws_iam_role" "rds_enhanced_monitoring" {

  name               = "rds-enhanced-monitoring-${var.name}"
  assume_role_policy = data.aws_iam_policy_document.monitoring_rds_assume_role.json

  permissions_boundary = var.permissions_boundary
}
```

**Comment by bryantbiggs** [comment]
Closed with #104
