### ISSUE TITLE
Add description for `snapshot_identifier` for the case when its changed after database has been created

### ISSUE THREAD

**Issue by jayai2014** [terraform-aws-modules/terraform-aws-rds-aurora#122]
Would it be a good idea to update the description for `snapshot_identifier`, for the case it's not used anymore once the database is already created?

**Comment by bryantbiggs** [comment]
hi @jayai2014 - could you elaborate a bit more on the issue you are facing?

**Comment by bryantbiggs** [comment]
closing this in favor of what is provided by the latest release of the upstream AWS provider https://github.com/hashicorp/terraform-provider-aws/pull/18013
