### ISSUE TITLE
VPC Security Groups Not Updated on Replace

### ISSUE THREAD

**Issue by Velgus** [terraform-aws-modules/terraform-aws-rds-aurora#127]
Using the `module.example_security_group.this_security_group_id` output from the Security Group module (https://github.com/terraform-aws-modules/terraform-aws-security-group) to apply security groups to this module fails to update if the security group is replaced for some reason (eg. description change).

The new replacement security group is created, but not attached to the Aurora cluster. The old group fails to delete, and stays attached to the Aurora cluster with all inbound and outbound rules removed.

I am able to manually fix it by adding the new SGs and removing the old ones to the Aurora cluster from the RDS Console, then deleting the old ones in the EC2 console, but this is not ideal.

**Comment by bryantbiggs** [comment]
hi @Velgus - this is due to the way security groups work. security groups are attached to the ENIs and if a security group is referenced by other security groups or still attached to other ENIs then it won't be able to delete it.

**Comment by Velgus** [comment]
The security group was replaced in the configuration in all locations though. Should TF not be able to handle the replacement gracefully?

Basically:
1. TF creates the new security group
2. Replace old security group with new security group in all locations
3. Delete old security group

Currently this replacement fails at step 2, instead it tries to force step 3 pre-emptively.

**Comment by bryantbiggs** [comment]
its technically not a terraform issue - its the way that AWS handles security groups and their attachment/detachment with ENIs - https://www.google.com/search?client=firefox-b-1-d&q=aws+terraform+security+group+failed+to+delete
