### ISSUE TITLE
Creating a serverless Aurora db with the rds-aurora module fails

### ISSUE THREAD

**Issue by hussamhadi** [terraform-aws-modules/terraform-aws-rds-aurora#130]
I was trying to create a serverless Aurora database using the rds-aurora `aurora` module. I noticed that on main.tf line 82, an `aws_rds_cluster_instance` would be created, even if we choose a serverless engine_mode. This is of course unsupported because we cannot associate an instance with serverless. 
This throws the error

```
Error: error creating RDS DB Instance: InvalidParameterValue: Instances cannot be added to Aurora Serverless clusters.
        status code: 400, request id: ...
```

My workaround was to download the Terraform script and comment out the part that creates the instance, but this is not a general or correct solution.

**Comment by craigsimon** [comment]
Just hit this myself.  Module will not work for serverless configurations.

[dev] terraform apply -auto-approve                                                                                                                master  ✗ ✱

Error: Missing required argument
  on dev.tf line 139, in module "db_west":
 139: module "db_west" {
The argument "instance_type" is required, but no definition was found.

**Comment by cf-sewe** [comment]
Have you set `replica_count         = 0` (from the serveless example)
As I read the code, that should avoid this issue.

**Comment by hussamhadi** [comment]
I tried this and it worked. Thank you for your support and time!

**Comment by Cedric-M** [comment]
GiHub link to the [terraform-aws-rds-aurora module serverless example](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/v3.5.0/examples/serverless/main.tf) just in case.

**Comment by nilfarzcc** [comment]
New to terraform and got this issue. adding replica_count = 0 worked for me. thank you.
