### ISSUE TITLE
getting InvalidParameterValue while using aurora-mysql as engine type

### ISSUE THREAD

**Issue by safdarq19** [terraform-aws-modules/terraform-aws-rds-aurora#131]
Terraform version 0.12.24

I am trying to create aurora mysql serverless rds with below configuration, running into error invalid parameter value when I use aurora-mysql. it works fine if i use engine as aurora. plan does not give me any error.

provider "aws" {
region = "us-east-1"
}
resource "aws_rds_cluster" "serverless" {
cluster_identifier = "serverless-dev"
engine = "aurora-mysql"
engine_mode = "serverless"
master_username = "dba_admin"
master_password = "changemepass"
skip_final_snapshot = true
db_subnet_group_name = "serverless-vpc"
}

Error: error creating RDS cluster: InvalidParameterValue: The engine mode serverless you requested is currently unavailable.
status code: 400, request id: 2294c942-fec5-4f45-a9e0-7520e33b73b8

**Comment by jurgenweber** [comment]
yeah, I am getting this...... what you do to fix it?

**Comment by safdarq19** [comment]
@jurgenweber amazon does not support serverless for 5.7 aurora version. I switched the engine from aurora-mysql to aurora, it works and had to go back and read documentation. did not pay close attention to document when I was trying to build 5.7 serverless aurora mysql cluster.

**Comment by jurgenweber** [comment]
yeah, I figured it out in another thread the api and doco is rubbish.
