### ISSUE TITLE
Relative links in readme.md break on terraform registry page

### ISSUE THREAD

**Issue by jwlogemann** [terraform-aws-modules/terraform-aws-rds-aurora#135]
The links to the examples in the readme.md use relative paths. This works fine on github, but on registry.terraform.io obviously not.

See https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/2.11.0 and click on any of the links under 'examples'

**Comment by bryantbiggs** [comment]
hi @jwlogemann - unfortunately this is a side-effect of the registry rendering the github repository
