### ISSUE TITLE
Provider constraint prevents from upgrading to aws provider 3.x

### ISSUE THREAD

**Issue by michaelaw320** [terraform-aws-modules/terraform-aws-rds-aurora#140]
`~>` constraint prevents updating to newer aws v3 provider. Is it intended?

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/589f07f5db3294d2d5b6e14a2cb2ed9feb7cd6f8/versions.tf#L4-L5

**Comment by antonbabenko** [comment]
Hi!

This is now fixed in [v2.21.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.21.0) which has been just released.
