### ISSUE TITLE
Issue when using the module to create a secondary cluster as part of a Global Aurora database

### ISSUE THREAD

**Issue by callaingit** [terraform-aws-modules/terraform-aws-rds-aurora#157]
Hi. There is an issue when using the module to create a secondary cluster as part of a Global Aurora database.

For the first cluster to join the Global database, fine. But the secondary cluster cannot be created because credentials are passed while they should not and we cannot prevent that behavior right now.

Even if we don't pass a master password, the module creates one and passes it to the aws_rds_cluster resource.

(because of the line master_password      = var.password == "" ? random_password.master_password.result : var.password in main.tf)

And we get:

Error: error creating RDS cluster: InvalidParameterCombination: Cannot specify user name for cross region replication cluster
	status code: 400, request id: 5b1d2557-43a7-4c8f-bcd0-9c3c6ba90369

The module must find a way not to pass a username or password when creating a secondary cluster on a global database.

**Comment by coddely** [comment]
You need to explicitly call the aurora module twice, once to create the primary instance with a password in the first region, and the second time without the password in the second region.  When creating the second cluster, I had to create a dependency on the first region to be created first with a "depends_on" flag:
depends_on = [module.primary_aurora]

**Comment by callaingit** [comment]
Yep, but it is not possible to bypass the random password generation logic defined by local.master_password which is used directly for the second cluster.

**Comment by callaingit** [comment]
I think the issue is that I was not even passing a username, but there is a default value of "root". I am trying this out right now (i.e. with a username = "" and no password at all - the local.master_password will kick in to provide one, but we'll see.

**Comment by coddely** [comment]
I created a variable "is_primary_region" and added that to the master password:
master_password = var.is_primary_region ? (var.password == "" ? random_password.master_password.result : var.password) : ""

When I call the module, I set it to "true":

module "primary_aurora" {
  source                               = "../../../modules/aurora"
  providers                          = {aws = aws.primary}
  create_global_cluster        = true
  is_primary_region             = true
  ...

module "secondary_aurora" {
  source                                = "../../../modules/aurora"
  depends_on                       = [module.primary_aurora]
  providers                           = {aws = aws.secondary}
  create_global_cluster         = false                           # only need to create a global cluster once
  is_primary_region              = false

**Comment by callaingit** [comment]
I was about to do a PR, but we had the same thing in mind more or less. I just want to confirm I have the same issue if I force a username to "" first.

**Comment by coddely** [comment]
username and password is set in the primary, not in the secondary module call.

the aurora module section looks like this"
  master_username      = var.is_primary_region ? var.username : ""
  master_password      = var.is_primary_region ? (var.password == "" ? random_password.master_password.result : var.password) : ""

**Comment by callaingit** [comment]
When forcing a username with "", we still have a similar issue (the first message in the issue description was about the user name, now with the password).

Error: error creating RDS cluster: InvalidParameterCombination: Cannot specify password for cross region replication cluster
	status code: 400, request id: 1e862703-6c9d-4046-983f-7637d2218ac7

**Comment by callaingit** [comment]
@coddely , do you want to do the PR or shall I attempt it (in line with the changes you propose)?

**Comment by callaingit** [comment]
I submitted PR #158

**Comment by dmattia** [comment]
I believe this functionality is accomplished by an existing PR: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/142
