### ISSUE TITLE
TF 0.13 Error: Unsupported Terraform Core version

### ISSUE THREAD

**Issue by sgasquet** [terraform-aws-modules/terraform-aws-rds-aurora#165]
Hi there,

Is there any plan actually to prepare the migration to terraform 0.13 ? 
Currently with 0.13 we encounter this issue of incompatibility : 
`Error: Unsupported Terraform Core version`

Thanks for your help ! 

Regards,
Sylvain :)

**Comment by antonbabenko** [comment]
Hi,

Terraform 0.12.6 and newer are already supported. Please verify which version of the module you are using.

**Comment by bryantbiggs** [comment]
hi @sgasquet I'm going to close this issue out for now - if you have more information/context to provide, please let us know. thanks!
