### ISSUE TITLE
Error while trying to create Aurora MySQL Serverless using snapshot

### ISSUE THREAD

**Issue by alka2** [terraform-aws-modules/terraform-aws-rds-aurora#167]
I am trying to create Aurora MySQL  serverless cluster from an snapshot and getting this error:

```
Error: error modifying RDS Cluster (test-db): InvalidParameterCombination: You currently can't modify BackupWindow with Aurora Serverless.
```
While there is no error if I create a database without `snapshot_identifier`

I am using [serverless](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/serverless/main.tf) example with only one change. I added:
```
snapshot_identifier = "test-snapshot"
```
`test-snapshot` was created from a cluster that was created using serverless example.

versions:
```
terraform-aws-rds-aurora: 2.29.0
terraform: 0.13.5
```

**Comment by bryantbiggs** [comment]
hi @alka2 - please see the error message provided by Terraform `You currently can't modify BackupWindow with Aurora Serverless`

**Comment by kartikrao** [comment]
@bryantbiggs - This happens even if no backup related inputs are set.

**Comment by bryantbiggs** [comment]
@kartikrao without any code I'm not sure how I can help. what I do know is that this https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master/examples/serverless works, perhaps that will help point you in the right direction

**Comment by kartikrao** [comment]
@bryantbiggs - Appreciate you responding back, if you take the [example code](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master/examples/serverless ) and add `snapshot_identifier` with the ARN of an existing database snapshot you'll be able to reproduce.

The deployment fails with the BackupWindow error even though no backup related settings have been specified

**Comment by alka2** [comment]
@kartikrao The workaround is:
```
preferred_backup_window = ""
```
Using this the backup window will be always be the default.

**Comment by kartikrao** [comment]
@alka2 - Thanks, I will try that today.

**Comment by bryantbiggs** [comment]
ah ok - thanks for the info @alka2 - I think we can do something about this

**Comment by TjeuKayim** [comment]
Thanks for sharing the workaround.
I needed to set a second option:

```tf
module "aurora" {
  # ...
  preferred_backup_window      = ""
  preferred_maintenance_window = ""
}
```

Otherwise, AWS returns this error:

```
│ Error: error modifying RDS Cluster (***): InvalidParameterCombination: You currently can't modify MaintenanceWindow with Aurora Serverless.
│       status code: 400, request id: ***
│ 
│   on .terraform/modules/db_cluster.aurora/main.tf line 50, in resource "aws_rds_cluster" "this":
│   50: resource "aws_rds_cluster" "this" {
│ 
```
