### ISSUE TITLE
Add the ability to ignore snapshot_identifier

### ISSUE THREAD

**Issue by ramirezag** [terraform-aws-modules/terraform-aws-rds-aurora#168]
It would be nice if this module supports creating a cluster from the most recent snapshot of the rds cluster for whatever purposes like for load testing or dev or staging db and then [ignore further new snapshots](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_cluster_snapshot#example-usage).

PS: I would like to work on this if this ticket makes sense :).

**Comment by bryantbiggs** [comment]
closing this in favor of what is provided by the latest release of the upstream AWS provider https://github.com/hashicorp/terraform-provider-aws/pull/18013
