### ISSUE TITLE
performance_insights_retention_period is not supported in the module

### ISSUE THREAD

**Issue by sporokh** [terraform-aws-modules/terraform-aws-rds-aurora#170]
Hello,

It looks like this option: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_retention_period is not supported in the module.
AWS allows you to select the retention period for performance insights from 7 days (default) to 2 years. Any chance that this could be added?

**Comment by bryantbiggs** [comment]
hi @sporokh that is for a standard RDS instance which we do not use in this module, this is for Aurora clusters and therefore we use cluster instance https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance - and this does not support that attribute
