### ISSUE TITLE
Question: What variables to pass to ECS task definition

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [terraform-aws-modules/terraform-aws-rds-aurora#173]
Hi Community,

This is my current setup:
1. I have an ECS Cluster across 2 azs which has templated ecs task definitions
2. I have an RDS cluster also across 2 azs
3. I have a ECS task definition template to which I inject the database name using `vars` like below:

```
data "template_file" "app" {
  template = file("./templates/ecs/app.json.tpl")

  vars = {
    app_image      = var.app_image
    host_port      = var.host_port
    container_port = var.container_port
    db_hostname    = <database instance end-point for a single az>
    fargate_cpu    = var.fargate_cpu
    fargate_memory = var.fargate_memory
    aws_region     = var.aws_region
  }
}
```

My question now is:
How can I modify this task definition for each az by passing in the RDS instance endpoint name for that az?
I see I have two options:
1. `module.db.this_rds_cluster_instance_ids` and use it to create multiple definitions using `count.index` and such?
2. `module.db. this_rds_cluster_endpoint` and point the `db_hostname` for the task definition to the cluster endpoint

Which path should I take? I'm not even sure if the above 2 options are valid. Is there something else I should be doing or am I on the right path?

I'd appreciate any advise from this community as I'm new to the terraform world.

**Comment by spatel96** [comment]
An RDS Cluster usually consists of a WRITER and READER.

When you create a cluster RDS generates separate endpoints for each purpose, e.g. a writer endpoint and reader endpoint.

In your case you have an application that will be hosted on AWS ECS Fargate and will run replica containers using a single task definition. That means you aren't supposed to have AZ specific configuration (you probably can accomplish this but I don't see why you'd need it).

To pass in the db_hostname you probably want to use the terraform output that this module produces:
**`this_rds_cluster_endpoint`**
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora#outputs

--

So something along the lines of:

```
data "template_file" "app" {
  template = file("./templates/ecs/app.json.tpl")

  vars = {
    app_image      = var.app_image
    host_port      = var.host_port
    container_port = var.container_port
    db_hostname    = module.rds_cluster.this_rds_cluster_endpoint
    fargate_cpu    = var.fargate_cpu
    fargate_memory = var.fargate_memory
    aws_region     = var.aws_region
  }
}
```

Hope that helps

**Comment by sfc-gh-pkommini** [comment]
Hi @spatel96,

Thank you for that key insight. So when you say aren't supposed to have AZ specific config:

Would this design be inaccurate?

**Comment by spatel96** [comment]
That diagram looks nearly about right, essentially yes, we do have an RDS instance per AZ. But I would have a single line going to a the "writer" and lines showing replication to the RO replicas in the other AZs.

The docs have a diagram that kind of shows this:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.html

**Comment by sfc-gh-pkommini** [comment]
That makes perfect sense! Closing this issue as this was really just a question. Thank you very much for your detailed answer with documentation.

Let me know if the below modified diagram looks right to you.

![image](https://user-images.githubusercontent.com/72515998/101815849-09b16d80-3ad5-11eb-8a33-240ee3787636.png)

**Comment by sfc-gh-pkommini** [comment]
Oh I just noticed you can RO in other AZs. I'll make that change.
