### ISSUE TITLE
allowed_security_groups value of 'count' cannot be computed

### ISSUE THREAD

**Issue by asaghri** [terraform-aws-modules/terraform-aws-rds-aurora#18]
Hello everyone,

I'd like to know how I can use the "allowed_security_groups" with outputs from other modules.
Currently, when I do this : 
`allowed_security_groups         = ["${module.bastion_access.bastion_security_group_id}"]`
I have the famous : `aws_security_group_rule.default_ingress: value of 'count' cannot be computed`

Thanks for your help !

**Comment by max-rocket-internet** [comment]
See here: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/11

**Comment by asaghri** [comment]
Thank you for your answer, the thing is I use a master module which has several modules in it.
So that's hard, too bad we can't use a "depends on" with modules...

**Comment by dekimsey** [comment]
Can you try this again with 1.8.0? There's a new field `allowed_security_groups_count` which should help you work-around the error.

**Comment by antonbabenko** [comment]
Closing this issue, as @dekimsey has pointed out it has been resolved for both Terraform 0.11 and 0.12 users.
