### ISSUE TITLE
MySQL Provider stopped working since v2.29.0

### ISSUE THREAD

**Issue by maartenschalekamp** [terraform-aws-modules/terraform-aws-rds-aurora#187]
Using the following mysql provider config on any versions after v2.28.0 the endpoint value is either not set or set to 127.0.0.1:3306. Not sure if the mysql provider will automatically use 127.0.0.1:3306 if the value is empty.
```
provider "mysql" {
  endpoint = module.this.this_rds_cluster_endpoint
  username = module.this.this_rds_cluster_master_username
  password = module.this.this_rds_cluster_master_password
  proxy    = "socks5://127.0.0.1:8123"
  version  = "~> 1.9"
}
```
Error when using v2.29.0
```
Error: Could not connect to server: socks connect tcp 127.0.0.1:8123->127.0.0.1:3306: EOF
```

Removing the provider and just checking the output it seems like the correct value is exported. So this is very strange.

```
terraform --version
Terraform v0.12.29
+ provider.aws v3.24.1
+ provider.mysql v1.9.0
+ provider.random v2.3.0
+ provider.sops v0.5.2
```

If more info is required please let me know.

**Comment by bryantbiggs** [comment]
hi @maartenschalekamp - unfortunately this module doesn't have anything to do with the MySQL provider. some things you might want to check are security group rules and any NACLs you might have in place on your network/resources

**Comment by maartenschalekamp** [comment]
just strange that using module version v2.28.0 it works perfectly fine, but not since version v2.29.0. So cant think of any reason why SG and NACL's will be affected by that.

**Comment by maartenschalekamp** [comment]
> hi @maartenschalekamp - unfortunately this module doesn't have anything to do with the MySQL provider. some things you might want to check are security group rules and any NACLs you might have in place on your network/resources

just strange that using module version v2.28.0 it works perfectly fine, but not since version v2.29.0. So cant think of any reason why SG and NACL's will be affected by that.

**Comment by bryantbiggs** [comment]
@maartenschalekamp do you have a reproduction we could look at, test?
