### ISSUE TITLE
Question about the MIT license

### ISSUE THREAD

**Issue by christiangjengedal** [terraform-aws-modules/terraform-aws-rds-aurora#19]
Will the module be released on registry.terraform.io with the current MIT license?
Curious about the implications of the 'Claranet Ltd' copyright notice.  
Is that where you work @FutureSharks ?

**Comment by antonbabenko** [comment]
It is already MIT and I don't think we have any reasons to change it in the future.

**Comment by max-rocket-internet** [comment]
Nothing to to with me (@FutureSharks is my other github account). The mention of Claranet comes in the standard MIT license from Github.
