### ISSUE TITLE
Few suggestions to improve

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-rds-aurora#2]
Remaining things to fix before big announcements on the registry:
- [ ] Add all outputs for all resources (get names from [official documentation](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html) for each resource))
- [ ] Review all variables for all resources (get names from [official documentation](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html) for each resource)). Also copy defaults which are in the official documentation.
- [ ] Make examples executable, add README there, add outputs. And run them all.

After the release (any time later):
- [ ] Review the code. It should be possible to create several RDS clusters with the same `name`, so use `name_prefix` or synonyms on all resources.
- [ ] Add conditional creation of optional resources (security group, db subnet group can be provided externally).
- [ ] Add conditional creation of RDS cluster also.

**Comment by max-rocket-internet** [comment]
> Add conditional creation of RDS cluster also.

How does that work? Without the cluster, there's no point in using the module?

**Comment by FutureSharks** [comment]
> Users may want to enable/disable creation of RDS clusters using the same code

OK gotcha 👍

**Comment by bryantbiggs** [comment]
I believe most (if not all) are complete so closing out
