### ISSUE TITLE
this_rds_cluster_master_username output is required to be sensitive for unknown reason

### ISSUE THREAD

**Issue by okobylianskyi** [terraform-aws-modules/terraform-aws-rds-aurora#212]
## Description

After Terraform upgrade v0.14 -> v0.15, `terraform plan` started to fail with 
```
Error: Output refers to sensitive values
│
│   on .terraform/modules/xxx/outputs.tf line 49:
│   49: output "this_rds_cluster_master_username" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```
Initially, the issue occurred with **terraform-aws-modules/rds-aurora/aws** v2.29.0, but upgrade to v4.1.0 didn't help.
Looks like there was a pull request with a similar issue https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/176 but it was closed. 
As it was mentioned in that pull request discussion, `master_username` field which is used by `this_rds_cluster_master_username output` is not marked as sensitive in `aws_rds_cluster` resource but nevertheless, the error occurs.

## Versions
 - Terraform: v0.15.0
 - Provider(s):
  provider registry.terraform.io/hashicorp/aws v3.37.0
  provider registry.terraform.io/hashicorp/local v2.1.0
  provider registry.terraform.io/hashicorp/random v3.1.0
  provider registry.terraform.io/hashicorp/template v2.2.0
 - Module:
 terraform-aws-modules/rds-aurora/aws v2.29.0 or v4.1.0

## Reproduction
- Use **terraform-aws-modules/rds-aurora/aws** module with Terraform v0.14
- Update Terraform to v0.15
- Run `terraform plan`

## Expected behavior
`terraform plan` finishes successfully.

## Actual behavior
`terraform plan` fails with an error:
```
Error: Output refers to sensitive values
│
│   on .terraform/modules/xxx/outputs.tf line 49:
│   49: output "this_rds_cluster_master_username" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

**Comment by pr1ntr** [comment]
There seems to be a breaking change in terraform .15 that requires all sensitive values to have the sensitive flag.

**Comment by JimBeam2019** [comment]
Yeah, I got that too. I simply add `sensitive   = true` in the `output "this_rds_cluster_master_username"` on **.terraform/modules/aurora/outputs.tf**, and it works through.

**Comment by pr1ntr** [comment]
@JimBeam2019 thats a non ideal solution because typically you shouldn't commit what is in the .terraform folders.
