### ISSUE TITLE
Importing a restored DB

### ISSUE THREAD

**Issue by shmick** [terraform-aws-modules/terraform-aws-rds-aurora#214]
I currently have an aurora postgresql DB deployed with this module. If I create a new DB from a cluster snapshot, is it possible to use terraform with this module to import the new DB so that I can continue to manage the new DB via terraform?

**Comment by bryantbiggs** [comment]
yes @shmick ! you can set the `snapshot_identifier` variable to point to your snapshot, either the snapshot name or ARN are acceptable

**Comment by shmick** [comment]
Thanks for the info @bryantbiggs, I wasn't aware that you could create a new DB from a snapshot_identifier with this module.

That's really helpful!

**Comment by bryantbiggs** [comment]
anytime, happy to help!
