### ISSUE TITLE
Export dbi_resource_id's

### ISSUE THREAD

**Issue by psmit** [terraform-aws-modules/terraform-aws-rds-aurora#217]
## Is your request related to a new offering from AWS?
No, it is already available on the aws_rds resources

## Is your request related to a problem? Please describe.
I want to use IAM authentication (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html) The ARN for giving access would need the DbiResourceID's of the rds instances. I'm not able to obtain these id's from the module at the moment.

## Describe the solution you'd like.

I would like to have an output for this module that has a list of dbi_resource_id's

## Describe alternatives you've considered.

I have considered using the rds datasources to get these ids, but they are not available in data sources; only in resources.

**Comment by bryantbiggs** [comment]
hi @psmit , this is already available https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/1dbbd998ae62436eb13918d09ac0882f01ebd8e2/outputs.tf#L66

**Comment by psmit** [comment]
My apologies, somehow I missed this!

**Comment by psmit** [comment]
Actually, I replied a bit fast now. The instance ids are actually not the same as the resource ids.  Could the resource ids be added as well?

**Comment by psmit** [comment]
The value is present on the resource:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#dbi_resource_id


(Unfortunately I can't reopen this issue myself)

**Comment by bryantbiggs** [comment]
ah ok, now I see the attribute

**Comment by bryantbiggs** [comment]
@psmit it was just added in the latest release if you want to give it a shot
