### ISSUE TITLE
instance_type_replica not honoured

### ISSUE THREAD

**Issue by svenlito** [terraform-aws-modules/terraform-aws-rds-aurora#220]
## Description

When creating a cluster where `instance_type` is set, `instance_type_replica` is ignored and `instance_type` is used for replica instances.

I believe this was introduced here https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/211

## Reproduction

create autoscaling example with `instance_type` and `instance_type_replica` defined.

## Expected behavior
`instance_type_replica` to be honoured.

## Actual behavior
`instance_type_replica` uses `instance_type` value

**Comment by rnrsr** [comment]
> When creating a cluster where instance_type is set, instance_type_replica is ignored and instance_type is used for replica instances.

I think this is intentional, from the `instance_type` description here: https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/latest?tab=inputs
it says:
>  If instance_type_replica is not set it will use the same type for replica instances

If you want different types used on your read replicas specify the `instance_type_replica` like so, i just tried it on 5.2.0:
```
  instance_type                = "db.t3.small"
  instance_type_replica        = "db.t3.medium"
```

gives me:

```
  # module.rds_my.module.rds-cluster.aws_rds_cluster_instance.this[0] will be updated in-place
  ~ resource "aws_rds_cluster_instance" "this" {
        id                              = "my-1"
      ~ instance_class                  = "db.r5.large" -> "db.t3.small"
      ~ performance_insights_enabled    = true -> false
        tags                            = {
            "Environment" = "dev"
            "Terraform"   = "true"
        }
        # (25 unchanged attributes hidden)
    }

  # module.rds_my.module.rds-cluster.aws_rds_cluster_instance.this[1] will be updated in-place
  ~ resource "aws_rds_cluster_instance" "this" {
        id                              = "my-2"
      ~ instance_class                  = "db.r5.large" -> "db.t3.medium"
      ~ performance_insights_enabled    = true -> false
        tags                            = {
            "Environment" = "dev"
            "Terraform"   = "true"
        }
        # (25 unchanged attributes hidden)
    }
```

**Comment by svenlito** [comment]
@rnrsr what I found is that whether I remove the `instance_type_replica` attribute or update it, my state doesn't change and it's stuck with whatever I've set `instance_type` to be. The example you're showing works because you're also changing the value of `instance_type`.

**Comment by svenlito** [comment]
> I don't think that's accurate, if i just try changing the `instance_type_replica` based on the above example, i get:
> 
> ```
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   # module.rds_offers.module.rds-cluster.aws_rds_cluster_instance.this[1] will be updated in-place
>   ~ resource "aws_rds_cluster_instance" "this" {
>         id                              = "offers-2"
>       ~ instance_class                  = "db.r5.large" -> "db.t3.medium"
>         tags                            = {
>             "Environment" = "dev"
>             "Terraform"   = "true"
>         }
>         # (26 unchanged attributes hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```

I get:

```bash
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by svenlito** [comment]
```sh
➔ t version
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.39.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.19.1
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html

```

**Comment by rnrsr** [comment]
wierd. tried a re-`init`?

**Comment by svenlito** [comment]
> Doing both, bumping to `0.14.4` and re-`init` now.

This didn't help.

**Comment by svenlito** [comment]
> interesting, what `replica_count` are you using?

Currently `replica_count = 1`

**Comment by svenlito** [comment]
> interesting, what `replica_count` are you using?
> 
> i notice this `count.index > 0 ? ` in the commit. Are you trying to reduce the replica_count to `1` at the same time as removing the `instance_type_replica`?

Oh, I think this is an off by one type of mistake then..

**Comment by svenlito** [comment]
I think this should be https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L119

```hcl
instance_class = try(lookup(var.instances_parameters[count.index], "instance_type"), count.index + 1 > 0 ? coalesce(var.instance_type_replica, var.instance_type) : var.instance_type)
```

**Comment by svenlito** [comment]
I think #193 is somewhat related
