### ISSUE TITLE
Ignore lifecycle changes

### ISSUE THREAD

**Issue by bfbay315** [terraform-aws-modules/terraform-aws-rds-aurora#230]
It would be helpful to be able to specify lifecycle changes to ignore at the plugin level.   Sometimes our infrastructure has minor drifts due to the way it is managed. For example, ignoring changes to tags or instance_type would be helpful.

**Comment by bryantbiggs** [comment]
completely agree @bfbay315, but unfortunately this is something that has come from Terraform core
