### ISSUE TITLE
No support for AWS IAM Authentication

### ISSUE THREAD

**Issue by Blokje5** [terraform-aws-modules/terraform-aws-rds-aurora#24]
There is no support for AWS IAM authentication in the module. This would be an improvement to the current module. Enabling it should be simple enough, however since not all versions and engines are supported it is probably good to validate the engine to see if it is possible.

**Comment by antonbabenko** [comment]
Agree, PR is welcome.

**Comment by Blokje5** [comment]
Great, I'll give it a go

**Comment by Blokje5** [comment]
I created a PR: #25
