### ISSUE TITLE
[Proposal] add aws_cloudwatch_log_group so we can define retention for each log group

### ISSUE THREAD

**Issue by yongzhang** [terraform-aws-modules/terraform-aws-rds-aurora#244]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
RDS will create a default cloudwatch log group without retention policy.

## Describe the solution you'd like.
We may create the log group in advance with required retention days, like this:
```
# Create log group in advance to enable log retention
resource "aws_cloudwatch_log_group" "group" {
  count             = var.create_cluster ? length(var.enabled_cloudwatch_logs_exports) : 0
  name              = "/aws/rds/cluster/${var.name}/${element(var.enabled_cloudwatch_logs_exports, count.index)}"
  retention_in_days = var.enabled_cloudwatch_logs_exports_retention_in_days
  tags = merge(var.tags, tomap({
    "Name" = format("%s", var.name)
  }))
}
```
Also, add `depends_on = [aws_cloudwatch_log_group.group]` to `resource "aws_rds_cluster" "this"`.

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by a0s** [comment]
So, the ticket was closed, but what the solution? I need log retention for logs of my dbs.

**Comment by disparo13** [comment]
Yes, what solution can I implement to set the retention period?
