### ISSUE TITLE
Setting writer = true in instances map does not result in assignment

### ISSUE THREAD

**Issue by brandonwbrown** [terraform-aws-modules/terraform-aws-rds-aurora#246]
## Description

Perhaps there is another way of doing this and I am misunderstanding the docs, but attempting to assign writer/reader assignments using the `writer` parameter does not result in re-assignment in the plan. 

## Versions
  version = "6.0.0"
 - Terraform:
  required_version = ">= 1.0.5"
 - Provider(s):
      source = "hashicorp/aws"
 - Module:
rds-aurora

## Reproduction
Deploy this module using two generalized instances
instances = { wr = {}, rd1 = {}}
then deploy using
  instances = {
    wr  = { writer = true }
    rd1 = { writer = false }
  }

It is also possible that this is reproducible with just setting the above on the first deploy. But not knowing how writers are assigned in the first place, I don't think testing this will be helpful for this case.

### Code Snippet to Reproduce
Full code below:

`module "rds-aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "6.0.0"

  name   = "${var.prefix}-aurora-db-pg-${var.aws_region}"
  engine = "aurora-postgresql"

  instance_class = "db.r5.large" // ignored in serverless
  instances = {
    wr  = { writer = true }
    rd1 = { writer = false }
  }

  autoscaling_enabled      = true
  autoscaling_min_capacity = 1
  autoscaling_max_capacity = 5

  engine_version = "13.3"

  vpc_id  = var.vpc_id
  subnets = data.aws_subnet_ids.private.ids

  create_security_group   = false
  allowed_security_groups = [aws_security_group.aurora_sg.id]
  allowed_cidr_blocks     = [for s in data.aws_subnet.private : s.cidr_block]

  monitoring_interval  = 60
  enable_http_endpoint = true
  backtrack_window     = 10
  skip_final_snapshot  = true
  storage_encrypted    = true
  apply_immediately    = true

  create_random_password = false
  master_password        = var.aurora_pw
  master_username        = var.aurora_usr

  database_name = replace(var.prefix, "-", "_")

  db_parameter_group_name         = aws_db_parameter_group.main_postgresql.id
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.main_postgresql.id

  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = merge(var.tags, tomap({ "Name" : "${var.prefix}-aurora-postgres-${var.aws_region}" }))

}`

## Expected behavior
I'd expect the wr instance to be a writer

## Actual behavior
the rd1 instance is still the writer after apply

### Terminal Output Screenshot(s)
N/A

## Additional context
N/A

**Comment by bryantbiggs** [comment]
hi @brandonwbrown - there isn't a means provided by AWS to designate which instance is the "writer" when creating a cluster with multiple instances. You can influence which instance *could end up being the writer by deploying a cluster with just 1 instance which means by default this will be the reader/writer instance, and then after adding additional instances which will be readers. you could also try setting one instance with `promotion_tier = 0` and the other instances to higher promotion tiers - I think this should work as well but didn't check at the moment to confirm.

remember, Aurora is a cluster built for HA and trying to depict which specific instance is the "writer" can be problematic (in a failover event, this instance will no longer be the writer for example).

I'm not sure where you saw the `writer` attribute/variable but that is not currently supported in this module

**Comment by brandonwbrown** [comment]
Thanks for the incredibly fast and helpful response @bryantbiggs. I'm sure it's just my lack of understanding. In application use then for Aurora, I'm assuming the best practice then is to use IAM DB auth with the cluster ARN (or SSL to the cluster) and not worry about the instances?

In terms of the `writer` variable, I assumed since the module uses the resource https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance as the instance block I could pass writer in via the instances block.

**Comment by bryantbiggs** [comment]
In terms of auth, IAM auth is something I am personally in favor of, but it honestly depends on you/your organizations preferences for credential/access management. 

For the endpoint to connect to, the recommended practice would be to use cluster endpoints. This module outputs the following:
- `cluster_endpoint` - reader/write endpoint, provided by default and will ensure that all connections are sent to the writer even if there is a failover event
- `cluster_reader_endpoint` - reader endpoint, provided by default and will send all requests to reader instances ONLY. this endpoint is great for automatically load balancing your read requests across however many read instances you have in your cluster

using these two endpoints will ensure your requests are routed appropriately (you just need to tell your app which to use for the appropriate use case, a lot of libraries today will have provisions for this distinction for efficient utilization of resources); you don't need to concern yourself with which instance is the writer (which is subject to change in a failover event)

also, there is provisions to create additional, custom endpoints within this module if so desired. this is a more advanced use case, see the example [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/3d996a2d64c2b782acef80a2ccfaa43644b5d150/examples/postgresql/main.tf#L66)

finally - the `writer` reference you see there is an attribute, not an argument. this is a value that would be available in the output when creating a `aws_rds_cluster_instance` directly.
