### ISSUE TITLE
Add ability to prevent deletion of database

### ISSUE THREAD

**Issue by paulseto** [terraform-aws-modules/terraform-aws-rds-aurora#262]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
Add a configuration setting `prevent_destroy = [true|false]

I didn't see a setting to prevent deletion of the database. I think there is a 
```
lifecycle {
   prevent_destroy  = true
}
```

**Comment by antonbabenko** [comment]
Terraform does not support variables inside `lifecycle` blocks, so this is not possible to implement in the module.

**Comment by paulseto** [comment]
In the terraform [documenatation](https://learn.hashicorp.com/tutorials/terraform/resource-lifecycle?in=terraform/state), there is an example of `prevent_destroy` being. Is this not applicable to rds?

**Comment by antonbabenko** [comment]
https://github.com/hashicorp/terraform/issues/3116 and https://github.com/hashicorp/terraform/issues/25534
