### ISSUE TITLE
Upgrading from 5.3 to 6.1 destroys all cluster instances

### ISSUE THREAD

**Issue by ruly1000** [terraform-aws-modules/terraform-aws-rds-aurora#264]
Attempting to upgrade aurora module from 5.3 to 6.1.3.  We have a single writer instance in the aurora cluster.  After upgrading the module, running a terraform results in a cluster with zero instances, the plan and apply destroys the one writer instance but does not create another one.  We have set autoscaling_enabled = true and autoscaling_min_capacity = 1, autoscaling_max_capacity = 4.

Desired behavior: the existing writer instance should be left alone as it satisfies the min capacity constraint. 

Simplified Terraform before module upgrade:

module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 5.3"

  name                   = "whatever"
  username               = "root"
  password               = "password"
  create_random_password = false
  database_name          = "testdb"

  engine         = "aurora-mysql"
  engine_version = "5.7.mysql_aurora.2.10.1"
  replica_count  = 1
  instance_type  = "db.r5.large"

  storage_encrypted          = true
  apply_immediately          = true
  auto_minor_version_upgrade = false
  deletion_protection        = true
  skip_final_snapshot        = false

  iam_database_authentication_enabled = true

  allowed_security_groups = [a security group ID defined in another terraform file]
  allowed_cidr_blocks     = [a list of CIDR blocks]
  vpc_id                  = our VPC ID
  subnets                 = our subnet IDs
  port                    = 3306

  enabled_cloudwatch_logs_exports = ["audit", "error", "general", "slowquery"]
}

Terraform after module upgrade:

module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 6.1"

  name                   = "whatever"
  master_username        = "root"
  master_password        = "password"
  create_random_password = false
  database_name          = "testdb"
 
 engine                   = "aurora-mysql"
  engine_version           = "5.7.mysql_aurora.2.10.1"
  autoscaling_enabled      = true
  autoscaling_min_capacity = 1
  autoscaling_max_capacity = 4
  instance_class           = "db.r5.large"

  storage_encrypted          = true
  apply_immediately          = true
  auto_minor_version_upgrade = false
  deletion_protection        = true
  skip_final_snapshot        = false

  iam_database_authentication_enabled = true

  allowed_security_groups = [a security group ID defined in another terraform file]
  allowed_cidr_blocks     = [a list of CIDR blocks, unchanged]
  vpc_id                  = our VPC ID, unchanged
  subnets                 = our subnet IDs, unchanged
  port                    = 3306

  enabled_cloudwatch_logs_exports = ["audit", "error", "general", "slowquery"]
}

The terraform plan gives some expected changes, but also one that is unexpected as follows.  This leaves the cluster with 0 instances since one is not created to replace it either:

```
  # module.aurora.aws_rds_cluster_instance.this[0] will be destroyed
  # (because resource does not use count)

```

**Comment by bryantbiggs** [comment]
hi @ruly1000  - have you reviewed the upgrade docs https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/UPGRADE-6.0.md ?

**Comment by ruly1000** [comment]
Yes, did not see anything there that would explain it.  We did not use the instances_parameters in 5.3 and are not using the instances map in 6.1.3, it isn't required.

**Comment by bryantbiggs** [comment]
> Yes, did not see anything there that would explain it. We did not use the instances_parameters in 5.3 and are not using the instances map in 6.1.3, it isn't required.

I don't quite follow - `instances map in 6.1.3, it isn't required` -> this is the only way to create a cluster with at least 1 or more instance in it https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/c1e2322e6a855d3be5c3da532a7acf570d9b92ee/examples/autoscaling/main.tf#L44

**Comment by ruly1000** [comment]
"instances" is in the "optional" section of the inputs for the module:

https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/latest?tab=inputs

When we were on 5.3 we did not specify the old property of "instances_parameters" and it did create the instance

**Comment by bryantbiggs** [comment]
`instances` being optional is a bit of a misnomer simply because a default value is provided. that default value is an empty map `{}` and an empty map will not create any instances. so yes, it is an optional parameter in the sense that if you do not provide it, the module will not throw an error. BUT, if you do not provide it, it will use the default which creates nothing.

**Comment by ruly1000** [comment]
Seems like instances should default to this instead of an empty map?

{ autoscaling_min_capacity = {} }

**Comment by ruly1000** [comment]
Also adding "instances = { 1 = {} }" still wants to destroy the old instance and create a new one, there is no reason the old instance should be destroyed

**Comment by bryantbiggs** [comment]
please read the upgrade guide - the previous 5.x and lower iteration used the Terraform `count` construct, and 6.x uses `for_each` hence the changes you are posting

**Comment by ruly1000** [comment]
Understand that now (thank you).  But there does not appear to be a way to prevent the existing instance from being destroyed when upgrading from 5.3 to 6.1.3.

**Comment by bryantbiggs** [comment]
`terraform state mv 'module.aurora.aws_rds_cluster_instance.this[0]' 'module.aurora.aws_rds_cluster_instance.this["0"]'`

**Comment by ruly1000** [comment]
That will work, but injects a manual step in our automation.  We'll have to deal with it though, thanks for the input.

**Comment by bryantbiggs** [comment]
it is all detailed in the upgrade guide (see bottom) and hence the breaking change and major version bump

**Comment by ruly1000** [comment]
Yes, I've read it, but didn't fully understand, now I do.  If I may make a suggestion (not sure if this is the right place).  There could be a new property "convert_instances_map_keys_to_integer" that if "true" would convert the instances map keys to integers during the iteration so that the tf mv isn't required?

**Comment by mission-lblaney** [comment]
@ruly1000 Did you loose data or did RDS handle that for you? I'm wondering if just let the instances be deleted if RDS will keep the cluster running by creating new instances first before deleting the old ones?
