### ISSUE TITLE
Serverless V2

### ISSUE THREAD

**Issue by travis-jorge** [terraform-aws-modules/terraform-aws-rds-aurora#269]
Will Serverless V2 be available when it goes GA later this year?
https://aws.amazon.com/rds/aurora/serverless/

**Comment by bryantbiggs** [comment]
if it is supported by the Terraform AWS provider - depending on what changes are necessary; yes or yes with a PR to support

**Comment by travis-jorge** [comment]
ok thank you it should be out to GA end of this month according to AWS Rep. Its currently available in us-east-1

**Comment by mik3h0** [comment]
Looks like this just went GA https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-aurora-serverless-v2/

**Comment by robmoss2k** [comment]
+1 for this.

**Comment by bryantbiggs** [comment]
once this is supported in the provider, we can add support here https://github.com/hashicorp/terraform-provider-aws/issues/24349

**Comment by steven-cherry** [comment]
+1 please

**Comment by bryantbiggs** [comment]
again - we cannot support until the provider supports. Please cast your 👍🏽 on the upstream issue since issues with the most votes are prioritized by the maintainers there

**Comment by njoerd114** [comment]
I opened the PR to support this in the provider. Once it's upstream, I can try integrating this into this module as well, since we're relying on it as well.

**Comment by nodomain** [comment]
Cool - looking forward to testing this.

**Comment by travis2090** [comment]
Looks like the upstream merge was complete 4.12.0

**Comment by njoerd114** [comment]
> Looks like the upstream merge was complete 4.12.0 hasn’t been released yet. Please be patient, we all want the feature asap, rest assured I’m monitoring the provider releases closely.

**Comment by houdinisparks** [comment]
4.12.0 has been released! https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.12.0 🤗

**Comment by travis-jorge** [comment]
@bryantbiggs @njoerd114 https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/288 I took a stab at a pr for this. Let me know if its not what your looking for.

**Comment by jensenbox** [comment]
I am very excited to have this! Thanks for all the hard work getting this released!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.0.0 :tada:

**Comment by bryantbiggs** [comment]
If you enjoy using `terraform-aws-modules` please give all your favorite modules a ⭐ and tell your friends! If your company/organization are heavy users of `terraform-aws-modules`, please consider sponsoring through one of the many avenues available - thanks all!
