### ISSUE TITLE
Output is missing the DB resource identifier

### ISSUE THREAD

**Issue by Blokje5** [terraform-aws-modules/terraform-aws-rds-aurora#27]
The resource identifier is needed when creating rds-db connect IAM policies for example and is returned by the aws_rds_cluster.cluster_resource_id. 

as an example of where this is needed:
```json
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
             "rds-db:connect"
         ],
         "Resource": [
             "arn:aws:rds-db:us-east-2:1234567890:dbuser:db-ABCDEFGHIJKL01234/db_user"
         ]
      }
   ]
}
```

currently there is no way to retrieve the resource identifier db-ABCDEFGHIJKL01234 from the module.

**Comment by antonbabenko** [comment]
@melechi has fixed this, it is now available in [v1.12.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v1.12.0).
