### ISSUE TITLE
Ignore lifecycle changes latest restorable time

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [terraform-aws-modules/terraform-aws-rds-aurora#271]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
Not a problem, just something annoying.
Since it is a moving point in time, every time we plan/apply, it appears as it is changing.

```hcl
  ~ resource "aws_db_instance" "this" {
      ~ latest_restorable_time                = "2022-02-15T15:10:00Z" -> "2022-02-16T17:00:00Z"

        # (unchanged attributes hidden)
        # (unchanged block hidden)
    }
```

## Describe the solution you'd like.

Something like:
```hcl
module "my-rds-cluster" {
  source                              = "terraform-aws-modules/rds/aws"
  version                             = "6.1.5"

  lifecycle_ignore_changes = [
    latest_restorable_time,
  ]
}
```

## Describe alternatives you've considered.
Using the resources that would be created by this module, but that would makes us outdated in tf's best practices.

**Comment by bryantbiggs** [comment]
there are no `aws_db_instance` resources created in this module, perhaps you meant to file in https://github.com/terraform-aws-modules/terraform-aws-rds ?

**Comment by bryantbiggs** [comment]
this is already set in the RDS module https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L121
