### ISSUE TITLE
Delete protection does not protect the Postgresql instances

### ISSUE THREAD

**Issue by simonweil** [terraform-aws-modules/terraform-aws-rds-aurora#275]
## Description

I've created a Postgresql cluster and set the delete protection including final snapshot creation.
But when I destroy the cluster the instances get deleted and only the cluster itself is protected.

I'm not sure this is actually a bug at all and perhaps this is the expected behavior as I do not see any possibility so set deletion protection on the instances resource nor in the UI.

Is this the expected behavior?
If so, how is my data protected?
Will a final snapshot with the data be created although no instance exists if the cluster is deleted?

Sorry if my questions are not in the scope of this repo...

## Versions

 - Terraform: 1.1.6

 - Provider(s):

```
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```
 - Module: latest version

## Expected behavior

The cluster instance deletion fails due to the delete protection

## Actual behavior

The cluster instances are deleted

**Comment by simonweil** [comment]
Should this issue be closed?

**Comment by bryantbiggs** [comment]
We can, or we can leave it. Right now its not actionable due to requiring provider support, but it does provide info if others come along looking for similar functionality
