### ISSUE TITLE
Ability to pass the parameters for "cluster parameter group" and "instance parameter group" like terraform-aws-rds module

### ISSUE THREAD

**Issue by haytham-salhi** [terraform-aws-modules/terraform-aws-rds-aurora#279]
## Is your request related to a new offering from AWS?
The feature is already available.

## Is your request related to a problem? Please describe.
The problem is we cannot pass the params in this module like terraform-aws-rds module. See https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#input_parameters

## Describe the solution you'd like.
We need to have the ability to pass the parameters like in this module: https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#input_parameters

## Describe alternatives you've considered.
Forking the module and adding the custom implementation there, which is smth not recommended.

## Additional context
N/A

**Comment by haytham-salhi** [comment]
Hi @bryantbiggs, any updates on this enhancement?

**Comment by bryantbiggs** [comment]
PRs are welcomed

**Comment by travis-jorge** [comment]
@haytham-salhi what paramaters do you want to pass in exactly? ill take a look.

**Comment by travis-jorge** [comment]
db_cluster_db_instance_parameter_group_name and db_cluster_parameter_group_name are already available so can you clarify what exactly you want. @haytham-salhi

**Comment by haytham-salhi** [comment]
Hi @travis-jorge , thanks for your comments. 

What you are saying is right regarding the `db_cluster_db_instance_parameter_group_name` and `db_cluster_parameter_group_name`. But what is requested is slightly different: we need to pass the input params themselves with their values instead of the group names. The idea is to provision the groups (optionally of course) with the needed params set. Exactly like terraform module for aws rds, please take a look here: https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest#input_parameters

Hope it is clear now. Thanks for your help!

**Comment by travis-jorge** [comment]
Ok I see yea when I get some time I’ll take a look at this.

**Comment by sean-casey-sb-we-should-enable-sso** [comment]
Just ran into this issue as well!

**Comment by CaseyLabs** [comment]
Just ran into this issue as well, and commenting to prevent the issue from becoming closed

**Comment by haytham-salhi** [comment]
Thanks @travis-jorge, have you got a chance to look at this?

**Comment by huzaifa-binafzal** [comment]
@travis-jorge @bryantbiggs we have created a PR to support this issue please review: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/307

**Comment by haytham-salhi** [comment]
Hi @antonbabenko and @travis-jorge, we have already implemented this feature here: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/307. Can you plz review and merge?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.3.0 :tada:
