### ISSUE TITLE
add argument enabled_cloudwatch_logs_exports as supported by terraform resource aws_rds_cluster

### ISSUE THREAD

**Issue by michaa76** [terraform-aws-modules/terraform-aws-rds-aurora#28]
add argument enabled_cloudwatch_logs_exports as supported by terraform resource aws_rds_cluster (https://www.terraform.io/docs/providers/aws/r/rds_cluster.html)

------------------------------------
`terraform version`
Terraform v0.11.10
+ provider.aws v1.59.0
+ provider.mysql v1.5.1
+ provider.null v2.0.0
+ provider.random v2.0.0

**Comment by antonbabenko** [comment]
Resolved in [v1.10.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v1.10.0).
