### ISSUE TITLE
Support for hashicorp/aws provider version >=4

### ISSUE THREAD

**Issue by xnick123** [terraform-aws-modules/terraform-aws-rds-aurora#281]
## Description
Support for hashicorp/aws provider version >=4, i'd like to update my environment but i cannot as long as this great module requires version 3

## Describe the solution you'd like.
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4"
    }

**Comment by bryantbiggs** [comment]
this module doesn't require v3, it sets a minimum required version but users are able to use v4 https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/a7a8bf111f6c1eeb4af0c5dfe53d65d05fc54e6c/versions.tf#L7

**Comment by xnick123** [comment]
oh my apologies, thank you!
