### ISSUE TITLE
Create an example of aurora_mysql_serverlessv2

### ISSUE THREAD

**Issue by MScottBlake** [terraform-aws-modules/terraform-aws-rds-aurora#290]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
4.12.0

## Is your request related to a problem? Please describe.

AWS recently released Aurora Serverless V2 and it was added in [v7.0.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/tag/v7.0.0). This update contains an example for Postgress Serverless V2, but no for MySQL. I am having a hard time identifying what changes I need to make to make it work.

## Describe the solution you'd like.

An updated [example](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master/examples/serverless) showing a functional module.

**Comment by antonbabenko** [comment]
We are open for the PR, so everyone is welcome to submit one. I ran the one for Postgres V2 before the release and didn't think there would be any big difference.

**Comment by ojhilt** [comment]
Hi, I'd also like to see this, including read-replica functionality too please!

**Comment by dannyOhNo** [comment]
Following along with the examples and documentation, I am also having difficulty creating a serverless v2 read-replica, with the primary node being provisioned.

**Comment by travis-jorge** [comment]
I can try to make the read replica docs later this week, but if you define two instances `instances = {
    1 = {}
    2 = {}
  }`

The second will be a read replica

**Comment by bryantbiggs** [comment]
closed in #295
