### ISSUE TITLE
security_group_egress_rules does not work well

### ISSUE THREAD

**Issue by liguofan1987** [terraform-aws-modules/terraform-aws-rds-aurora#299]
Versions:

registry.terraform.io/terraform-aws-modules/rds-aurora/aws 7.2.0 
hashicorp/aws v4.16.0.
Terraform v1.1.6
on darwin_amd64

When I set up security_group_egress_rules, terraform report a lot of similar errors below. lookup() requires a map as the first argument but the source code uses the each.value, which seems geting every value I set. A little bit wired, could you help, please?

 security_group_egress_rules = {
    type              = "egress"
    from_port         = 0
    to_port           = 0
    protocol          = "tcp"
    cidr_blocks       = "10.2.0.0/16"
    description       = null
    ipv6_cidr_blocks  = "::/0"
  }

....
Error: Invalid function argument
│ 
│   on .terraform/modules/aurora_pubhub_stage02/main.tf line 348, in resource "aws_security_group_rule" "egress":
│  348:   source_security_group_id = lookup(each.value, "source_security_group_id", null)
│     ├────────────────
│     │ each.value is "tcp"
│ 
│ Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.
╵
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/aurora_pubhub_stage02/main.tf line 348, in resource "aws_security_group_rule" "egress":
│  348:   source_security_group_id = lookup(each.value, "source_security_group_id", null)
│     ├────────────────
│     │ each.value is "egress"
│ 
│ Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.
╵
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/aurora_pubhub_stage02/main.tf line 348, in resource "aws_security_group_rule" "egress":
│  348:   source_security_group_id = lookup(each.value, "source_security_group_id", null)
│     ├────────────────
│     │ each.value is "0"
│ 
│ Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.
.......

**Comment by bryantbiggs** [comment]
you should change to 

```hcl
security_group_egress_rules = {
  one = {
    from_port        = 0
    to_port          = 0
    cidr_blocks      = ["10.2.0.0/16"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```

**Comment by liguofan1987** [comment]
Cool. Thank you!
