### ISSUE TITLE
Postgres example fails

### ISSUE THREAD

**Issue by medwig** [terraform-aws-modules/terraform-aws-rds-aurora#30]
Running the postgres example fails on `terraform apply` with this error message:

`* aws_rds_cluster.this: error creating RDS cluster: InvalidParameterCombination: Engine aurora-postgresql 9.6.3 does not support exporting to CloudWatch Logs. For supported engine versions, see the documentation.
`

**Comment by antonbabenko** [comment]
Thanks for opening this issue! This issue happens after #29 was merged.

@medwig or @michaa76 Could you please update examples with the correct values in all examples?

**Comment by officel** [comment]
Perhaps Aurora PostgreSQL is not yet compatible with Cloudwatch log export?

https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Integrating.html

Aurora MySQL
https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.CloudWatch.html

**Comment by kpahi** [comment]
Failed to run `terraform plan` with `enabled_cloudwatch_logs_exports` for `aws_rds_cluster`.

engine     = "aurora-postgresql"
version    = "9.6.9"

Thanks

**Comment by antonbabenko** [comment]
Fixed in [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.0.0) which works with Terraform 0.12.
