### ISSUE TITLE
Allow me to conditionally set the number of instances depending on environment

### ISSUE THREAD

**Issue by james-green-affinity** [terraform-aws-modules/terraform-aws-rds-aurora#304]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.

## Is your request related to a problem? Please describe.

Currently I have Aurora V2 defined like this for all environments:
`
  instance_class = "db.serverless"
  instances = {
    one = {
      availability_zone = "eu-west-2a",
      writer = true
    }
    two = {
      availability_zone = "eu-west-2b"
    }
  }
`

Just on my test environment I would like this instead:
`
  instance_class = "db.serverless"
  instances = {
    one = {
      availability_zone = "eu-west-2a",
      writer = true
    }
  }
`

## Describe the solution you'd like.

A solution that will allow me to conditionally define the number of instances per environment.
## Describe alternatives you've considered.

I have tried to make use of:
var.is_dev == "true" ? json : json
count = 0

However I could not get either of these terraform conditionals to work.

## Additional context

I would like to save money on my Test environment

**Comment by CaseyLabs** [comment]
I recently ran into this issue as well. On a previous version of this module, I used to set a conditional on `replica_count`:

```
replica_count = var.enable_high_availability ? var.number_of_replicas : 0
```
Which is now deprecated in the latest version of the module it appears.

Suggestion: add an example of a similar configuration to the `instances = {}` config map?
