### ISSUE TITLE
aurora-postgresql in serverless mode does not allow to set engine version and do upgrades

### ISSUE THREAD

**Issue by dejwsz** [terraform-aws-modules/terraform-aws-rds-aurora#313]
I just created RDS postgers with engine aurora-postgresql in serverless mode. In this case engine version is ignored and DB is creted with lowest version 10.18. This is really weird. What should I do to have the latest engine instead in this mode? Or how should I enforce update/upgrade with this TF module?

**Comment by anrglv** [comment]
same problem with 13.6 version

**Comment by dejwsz** [comment]
It looks like it only allows to choose the version for "provisioned" mode - later you need to upgrade to "serverless" mode in aws console and just import changes to TF. Looks like TF module is not fully compliant and cannot support all cases around this.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.4.0 :tada:

**Comment by dejwsz** [comment]
nice to see that!
