### ISSUE TITLE
Allow defining rds instance `multi_az`

### ISSUE THREAD

**Issue by pre** [terraform-aws-modules/terraform-aws-rds-aurora#315]
Provide option to set [multi_az](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#multi_az) for RDS `aws_db_instance` please. 

Also allow providing the [storage_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#rds-multi-az-cluster)  available for multi-az cluster.

Related: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/314

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.4.0 :tada:
