### ISSUE TITLE
Assigning master password does not get set on cluster

### ISSUE THREAD

**Issue by shawn-motley-dexcare** [terraform-aws-modules/terraform-aws-rds-aurora#318]
## Description

Using the RDS Aurora provider
source  = "terraform-aws-modules/rds-aurora/aws"
version = "7.3.0" 

Setting the master password like this:
master_password = random_password.secrets_password_generator.result

We have to go to the instance in AWS and reset password to the same one that is supposed to be set at provisioning in order to gain access.  

Any help would be appreciated

**Comment by bryantbiggs** [comment]
you'll need to set `create_random_password` to `false`

**Comment by shawn-motley-dexcare** [comment]
ahh thank you
