### ISSUE TITLE
Insure writer instance matches up with designated instance class

### ISSUE THREAD

**Issue by jim-leary** [terraform-aws-modules/terraform-aws-rds-aurora#328]
## Is your request related to a problem? Please describe.
I have done a number of test that show `{ for k, v in local.test_data : k => v ... } ` does not return map keys in lexicographical order.  Example:

```
locals {
   primary_prod_instances = {
      a-writer = {
        instance_class = "db.r6g.2xlarge"
        promotion_tier = 0
      }
      b-reader1 = {
        promotion_tier = 1
      }
      c-reader2 = {
        promotion_tier = 2
      }
    }
} 
```
is provided as the input value for the "var.instances" parameter to this module.

## Describe the solution you'd like.
There should be functionality defined where a writer instance is created first, followed by one or more readers.  I can only think of one way to do this, and that is making two aws_rds_cluster_instance calls, the first filtering on a value of "writer" = true, and then the second call filtering out the key/value with "writer" = true.

**Comment by bryantbiggs** [comment]
There is nothing that states that terraform maps are lexicographically ordered (there's no ordering, it's random), and likewise the writer instance is chosen by a race condition unless a priority is set

**Comment by jim-leary** [comment]
@bryantbiggs Care to cite the documentation regarding this "race condition" and "priority" setting?

**Comment by bryantbiggs** [comment]
I'll leave that as an exercise for yourself to get acquainted with the RDS service 😉

**Comment by jim-leary** [comment]
> I'll leave that as an exercise for yourself to get acquainted with the RDS service 😉

@bryantbiggs so the answer is no - and you're full of crap.

**Comment by antonbabenko** [comment]
@jim-leary This is not an acceptable way to say thanks. Bye!
