### ISSUE TITLE
support having a flag for global replication to a separate region?

### ISSUE THREAD

**Issue by bjm88** [terraform-aws-modules/terraform-aws-rds-aurora#33]
want to use the flag that AWS console offers to ask for replication not just to live master slave/replica in cluster, but also backup to separate region (not running db, just data/files).  Is there option for that?  Its part of DR plan type of requirement...

**Comment by fliphess** [comment]
We use: https://github.com/awslabs/rds-snapshot-tool/  to do this instead of replication we sync the snapshots to another region.

**Comment by bryantbiggs** [comment]
hi @bjm88 - unfortunately this feature is not yet supported in the upstream AWS provider so we cannot add it to the module
