### ISSUE TITLE
Unable to assign writer/reader as identifier to the instances

### ISSUE THREAD

**Issue by vesubramanian** [terraform-aws-modules/terraform-aws-rds-aurora#333]
## Description

When trying to provision instances during the cluster provisioning, I don't simply want an index suffixed to the cluster as the identifier for writer & reader instances. Since I am not able to control the order in which reader/writer gets provisioned, I am forced to use the existing convention (cluster-identifier & index). Need a solution for this.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

- Module version [Required]: 7.5.1

- Terraform version:
1.1.4
- Provider version(s):
aws >4.12.0

## Reproduction Code [Required]

`instances = {
    01 = {
      identifier     = format("%s%s",var.cluster_name,"-writer") 
      cluster_identifier = var.cluster_name
      engine_version = var.engine_version
      engine = var.engine
    }
    02 = {
      identifier     = format("%s%s",var.cluster_name,"-reader-1") 
      cluster_identifier = var.cluster_name
      engine_version = var.engine_version
      engine = var.engine
    }
  }
}`

terragrunt apply

## Expected behavior

Writer identifier should be <cluster-name>-writer
Reader identifier should be <cluster-name>-reader-1

## Actual behavior

Writer identifier is <cluster-name>-reader-1
Reader identifier is <cluster-name>-writer

**Comment by bryantbiggs** [comment]
that is not how a cluster works - you are presented with read/write and read-only endpoints, that is how a cluster is intended to be used. in a cluster, the writer instance can be swapped to another instance for various reasons so do not rely on the instance, use the endpoints. You can also add more endpoints to suit

**Comment by vesubramanian** [comment]
Thanks a lot for the prompt response. However, from the UI, I can add a reader. How do I achieve it via Terraform? Please suggest.

**Comment by bryantbiggs** [comment]
yes, each additional instance added to the map of `instances` will be added as a reader instance https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/2cdbaad7df90c764d143b2801f124ace566e7179/examples/postgresql/main.tf#L31-L39

**Comment by vesubramanian** [comment]
Thanks again for the quick response. So, the first instance (1) in the list will be writer? I am curious because 1={}, 2={}, 3={}, can cause 1 and 2 to be readers and 3 to be writer?

**Comment by bryantbiggs** [comment]
Again, there is no guarantee that `1` will be the writer, its a matter of which instance comes up first and claims the writer role. Do not think about which instance is the writer, just use the endpoints to talk to the read/write endpoint or the read-only endpoint

**Comment by vesubramanian** [comment]
Ok. Thank you again for the prompt response.
