### ISSUE TITLE
Unable to create replica cluster

### ISSUE THREAD

**Issue by stecog** [terraform-aws-modules/terraform-aws-rds-aurora#336]
I need create an Aurora replica from an RDS instance, I NOT specify any username but have this error
`Error: creating RDS Cluster (my-aurora-mysql): InvalidParameterCombination: Cannot specify user name for instance cluster replication cluster`
## Versions

- Module version:
7.6.0
- Terraform version:
1.3.4
- Provider version(s):
"hashicorp/aws" 4.33.0

## Reproduction Code [Required]

```
module "replica-aurora-mysql" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "7.6.0"
  name = "my-aurora-mysql"
  engine = "aurora-mysql"
  engine_version = "5.7.mysql_aurora.2.10.2"
  instance_class = "db.t4g.medium"
  instances = {
    one = {}
  }
  port = 3306
  create_db_subnet_group = false
  db_subnet_group_name = module.sta-rds-mysql.db_subnet_group_id
  subnets = module.vpc.private_subnets
  vpc_id = module.vpc.vpc_id
  vpc_security_group_ids = [module.sta-mysql-sg.security_group_id]
  preferred_maintenance_window = "Sun:01:00-Sun:02:00"
  preferred_backup_window = "03:00-06:00"
  backup_retention_period = 4
  skip_final_snapshot = true
  deletion_protection = true
  performance_insights_enabled  = false
  publicly_accessible = false
  create_db_parameter_group = false
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.staging-aurora-mysql57.id
  apply_immediately = true
  replication_source_identifier = module.sta-rds-mysql.db_instance_arn
}
```
From output of terraform plan i see that the `master_username` is set and is `root`, maybe is default, attaching image

![2022-11-10_13-06](https://user-images.githubusercontent.com/76922549/201087838-658ec6b0-1648-43fa-b71b-cccd9f6baccc.png)

**Comment by nikolay** [comment]
I am having the same issue. And found this workaround:

```
create_random_password = false
master_username        = null
```

**Comment by stecog** [comment]
> I am having the same issue. And found this workaround:
> 
> ```
> create_random_password = false
> master_username        = null
> ```

Thank you!
