### ISSUE TITLE
Add cloudwatch log group retention period parameter

### ISSUE THREAD

**Issue by pmcenery** [terraform-aws-modules/terraform-aws-rds-aurora#340]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Currently the Cloudwatch log group is automatically created with a retention period of "Never expire". This is not ideal as it leads to unexpected costs.

## Describe the solution you'd like.
In line with other `terraform-aws-rds` modules, it would be nice to specify the log group creation and retention period.

## Describe alternatives you've considered.
- Manually changing the retention period. Not infra-as-code :(
- Add a `aws_cloudwatch_log_group` resource manually outside the module. Could lead to situation where the log group has been automatically created and the resource outside the module fails.

## Additional context
It should be easy to add the functionality copy-paste from one of the other official modules to support this functionality.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.7.0 :tada:
