### ISSUE TITLE
 InvalidParameterCombination: Cannot find version 8.0.mysql_aurora.3.02.2 for aurora

### ISSUE THREAD

**Issue by bhanutummala1** [terraform-aws-modules/terraform-aws-rds-aurora#345]
Hello,

We are using this module(version 7.2.1) to create RDS MySQL aurora cluster and we recently upgraded to engine version to "8.0.mysql_aurora.3.02.2" manually. The highest version this module supports is 5.7.mysql_aurora Is there a solution to accommodate 8.0.
Any recommendations you can provide on this?

Thank You!

**Comment by bryantbiggs** [comment]
> The highest version this module supports is 5.7.mysql_aurora
This module does not restrict which versions are available - where are you seeing this?

**Comment by bhanutummala1** [comment]
**: InvalidParameterCombination: Cannot find version 8.0.mysql_aurora.3.02.2 for aurora**

This is the error we see in the code build when trying to upgrade the version from MySQL 5.6 to MySQL 8.0

**Comment by bryantbiggs** [comment]
This is not related to the module

**Comment by bhanutummala1** [comment]
Error: creating RDS Cluster: InvalidParameterCombination: Cannot find version 8.0.mysql_aurora.3.02.2 for aurora
│   status code: 400, request id: 2c000dc4-49ce-4b4e-806a-956ed4a4630b
│ 
│   with module.aws_rds_cluster.this[0],
│   on .terraform/modules/rds_cluster/main.tf line 47, in resource "aws_rds_cluster" "this":
│   47: resource "aws_rds_cluster" "this" {

**Comment by bhanutummala1** [comment]
This issue is resolved. The engine name for Aurora MySQL 2.x is aurora-mysql; the engine name for Aurora MySQL 1.x continues to be aurora.

so in my case
