### ISSUE TITLE
How to handle minor version upgrades with Global cluster involved

### ISSUE THREAD

**Issue by nhawkins04** [terraform-aws-modules/terraform-aws-rds-aurora#357]
## Description

AWS is getting more aggressive about [deprecating specific MySQL engine versions](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.20Updates.html). We are using this module and also deploying a [global-cluster similar to the example provided in this project](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master/examples/global-cluster). Since [auto_minor_version_upgrade is not supported on global clusters](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Patching.html#AuroraMySQL.Updates.AMVU) and AWS will be forcing a minor update of specific MySQL versions starting on April 3, 2023 we are trying to prepare our Infrastructure as Code for dealing with this accordingly. 

I am opening this bug (question) to understand if there is an expected way to manage minor version upgrades on Aurora clusters with global-databases (and AWS potentially force upgrading databases) that were built with Infrastructure as code. [The process for minor version upgrades with global clusters](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-upgrade.html#aurora-global-database-upgrade.minor) seems to not be IAC friendly and more of a manual process since it requires temporarily removing secondary regions from the global cluster, performing the upgrade, and adding it back to the global cluster then moving to primary. How can we expect to go through this process and keep IAC sane for the next run? 

Is the process going to be:
* relax the version constraints as explained [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/286#issuecomment-1456380420) on our IAC projects that we pass to the global-cluster and use the global-cluster engine version as input to the aurora module as demonstrated in [this example](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/global-cluster/main.tf)
* Follow [this process](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Patching.html#AuroraMySQL.Updates.Patching.ModifyEngineVersion) (for MySQL), manually, in the AWS console to upgrade the minor engine version since this type of orchestration is not possible with Terraform or AWS forces an upgrade due to deprecation schedule
* Due to our relaxed version constraint when IAC runs again all will be well? 

✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: "~> 5.0"

- Terraform version: "1.3.8"

- Provider version(s): aws "~> 4.0"

## Reproduction Code [Required]

NA - this is a process question.

NA - this is a process question

## Expected behavior

I should be able to follow a procedure that will be friendly with Infrastructure as Code (Terraform) to update minor versions on my clusters and global cluster and/or deal with AWS deprecation schedules accordingly. 

## Actual behavior

Uncertain about the process and how Terraform will handle clusters updated forcibly by AWS due to deprecation schedules. 

### Terminal Output Screenshot(s)

NA

**Comment by bryantbiggs** [comment]
thanks @nhawkins04 - any info you find out might be helpful to other users if you are open to adding some docs. it may not be frequently asked but we do have FAQs in other repos, we could start by adding something there if you are interested in contributing
