### ISSUE TITLE
"snapshot_identifier": conflicts with global_cluster_identifier

### ISSUE THREAD

**Issue by fplotnikov** [terraform-aws-modules/terraform-aws-rds-aurora#358]
## Description

During restore from the snapshot error appear:
"snapshot_identifier": conflicts with global_cluster_identifier

All works fine if snapshot restore doesn't require.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Tested on different module version.
Also updated AWS provider to the latest available 4.60.0 which has this issue in the description and marked as fixed - it doesn't help. 

## Versions

- Module version [Required]: 7.7.0

- Terraform version:
v1.3.4
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0

## Reproduction Code [Required]

Run RDS creation/update with defined variable - snapshot_identifier

## Expected behavior

Create RDS from snapshot.

## Actual behavior

Got an error on PLAN run:
│ "snapshot_identifier": conflicts with global_cluster_identifier

**Comment by bryantbiggs** [comment]
ref https://github.com/hashicorp/terraform-provider-aws/pull/30158

**Comment by pimperator** [comment]
I'm also affected by this: provider version 4.60.0. 
workaround is to go with 4.59.0

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.0.0 :tada:
