### ISSUE TITLE
Cannot create cluster due to missing username since 8.0.0

### ISSUE THREAD

**Issue by alencar** [terraform-aws-modules/terraform-aws-rds-aurora#368]
Version information
- Terraform 1.4.4
- Terraform AWS Provider 4.61.0
- Terraform AWS  Modules / terraform-aws-rds-aurora 8.0.0/8.0.1

With the version 8.0.0+, creating RDS clusters fails with

```
│ Error: creating RDS Cluster (tableau-cntga5as): InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank.
│       status code: 400, request id: 6fc7b80b-fcc5-4f4b-a74c-daf35bdee9e3
│ 
│   with module.database.aws_rds_cluster.this[0],
│   on .terraform/modules/database/main.tf line 37, in resource "aws_rds_cluster" "this":
│   37: resource "aws_rds_cluster" "this" {
│ 
╵
```

Error is due to incorrectly conditioning the MasterUsername here:
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/0dd4a5c9d59af0aeae1956caef00d6dff51ea1e8/main.tf#L71

MasterUsername must be provided even when using Secrets Manager to manage Master User credentials[1] unless other conditions are present and only the Password is to be omitted.

Conditions
verbatim: 
```
[master_username](https://registry.terraform.io/providers/hashicorp/aws/4.61.0/docs/resources/rds_cluster#master_username) - (Required unless a snapshot_identifier or replication_source_identifier is provided or unless a global_cluster_identifier is provided when the cluster is the "secondary" cluster of a global database) Username for the master DB user. Please refer to the [RDS Naming Constraints](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints). This argument does not support in-place updates and cannot be changed during a restore from snapshot.
```

That would be:
Snapshot / Replication source case                                                    Secondary in a Global cluster case
(var.snapshot_identifier OR var.replication_source_identifier) OR (var.global_cluster_identifier AND !var.is_primary_cluster)

[1] https://registry.terraform.io/providers/hashicorp/aws/4.61.0/docs/resources/rds_cluster

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.0.2 :tada:

**Comment by arnau-fauquer** [comment]
I'm having this issue in version 8.0.2


module "db" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "~> 8.0.2"

  name              = lower(var.company_name)
  engine            = data.aws_rds_engine_version.postgresql.engine
  engine_mode       = "provisioned"
  engine_version    = data.aws_rds_engine_version.postgresql.version
  storage_encrypted = true

  vpc_id               = module.vpc.vpc_id
  db_subnet_group_name = module.vpc.database_subnet_group_name
  security_group_rules = {
    vpc_ingress = {
      cidr_blocks = module.vpc.private_subnets_cidr_blocks
    }
  }

  monitoring_interval = 60

  apply_immediately   = true
  skip_final_snapshot = true

  serverlessv2_scaling_configuration = {
    min_capacity = 2
    max_capacity = 10
  }

  instance_class = "db.serverless"
  instances = {
    one = {}
    two = {}
  }

  tags = {
    Name        = var.company_name
    Environment = "common"
  }
}

Error: creating RDS Cluster (demo): InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank.
│       status code: 400, request id: f4becad3-3ce1-43c1-84e1-a5580e8c1b97
│ 
│   with module.-----.module.db.aws_rds_cluster.this[0],
│   on .terraform/modules/------.db/main.tf line 37, in resource "aws_rds_cluster" "this":
│   37: resource "aws_rds_cluster" "this" {

**Comment by arnau-fauquer** [comment]
Tx @alencar, I didn't read the https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/UPGRADE-8.0.md my bad
