### ISSUE TITLE
Feature to specify the security group name

### ISSUE THREAD

**Issue by hydeenoble** [terraform-aws-modules/terraform-aws-rds-aurora#372]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I am trying to import an already existing RDS cluster, and I have an attached security group that is not the same as the name of the cluster and also not `null`. Setting `security_group_use_name_prefix` to `true` recreates the security group because of the `name_prefix` and setting it to false recreates the security group because of the `name.`  

## Describe the solution you'd like.

I want to be able to manually specify the security group name for the SG created by this module.

## Describe alternatives you've considered.

For now, I am going with the resolution of setting `create_security_group` to false and creating a separate SG to attach to the RDS.

**Comment by bryantbiggs** [comment]
I would suggest either not letting the module create the security group or let the module create the security group and transfer the rules over from the existing security group to the new one (you can have multiple security groups with the same rules to support the transition without interruption)
