### ISSUE TITLE
Resource Specific Tags 

### ISSUE THREAD

**Issue by emily-ganze** [terraform-aws-modules/terraform-aws-rds-aurora#373]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - all versions

## Is your request related to a problem? Please describe.
Enabling DevOps Guru to analyze RDS instances requires a tag to be listed on resources. Currently there is no way to only specify tags for the cluster and instances.

## Describe the solution you'd like.
Have a var (new or using the cluster_tags var) to add tags to the instance(s).

## Describe alternatives you've considered.
Manual creation of tags makes the state out of sync which removes tags. Creating a resource for aws_db_instance outside of the module requires more than just the instance ID and tags.

**Comment by bryantbiggs** [comment]
There is `cluster_tags` to add tags just to the cluster https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/4380f14c101b145e4b691bcb465b7978b0e44fdc/main.tf#L127

And each instance definition allows for custom tags to be set https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/4380f14c101b145e4b691bcb465b7978b0e44fdc/main.tf#L179

What else is missing?

**Comment by emily-ganze** [comment]
The var.tags adds the same tags to all resources - subnet groups, security groups, etc. which I do not want to have the same tags as the instances/cluster.

**Comment by bryantbiggs** [comment]
no, not `var.tags`, its the 2nd value that is getting merged with `var.tags`. `var.tags` as you stated is added to all resources, but the 2nd `try(each.value.tags, {})` allows you to set tags to just that specific resource instance. Like this

```hcl
  instances = {
    blue = {
      instance_class      = "db.r5.2xlarge"
      publicly_accessible = true
      tags = {
        color = "blue"
      }
    }
    green = {
      identifier     = "static-member-1"
      instance_class = "db.r5.2xlarge"
      tags = {
        color = "green"
      }
    }
```

Only the `blue` instance will have the tag `{color: blue}`, and only the `green` instance will have the tag `{color: green}`, nothing else will have those tags

**Comment by emily-ganze** [comment]
Ah I see, I added the nested tags in `instances` like below but TF did not make the change - `No changes. Your infrastructure matches the configuration.`

``` terraform
instances = {
  one = {
    tags = {
      Devops-Guru-RDS = "true"
    }
  }
}

**Comment by emily-ganze** [comment]
Now I'm getting quite a few errors about vars for instances:
```
Error: Invalid function argument
│ 
│   on .terraform/modules/db.cluster/main.tf line 163, in resource "aws_rds_cluster_instance" "this":
│  163:   copy_tags_to_snapshot                 = lookup(each.value, "copy_tags_to_snapshot", var.copy_tags_to_snapshot)
│     ├────────────────
│     │ var.copy_tags_to_snapshot is null
│ 
│ Invalid value for "default" parameter: the default value must have the same type as the map
│ elements.

**Comment by bryantbiggs** [comment]
It will be difficult to tell without a reproduction - otherwise I will just be guessing at best

**Comment by emily-ganze** [comment]
I'm able to reproduce these errors everytime I have tags listed for one instance and not the other:
```terraform

  instances = {
    one = {
      tags = {
        Devops-Guru-RDS = "true"
      }
    }
    two = {}
  }
