### ISSUE TITLE
feature request: default_egress rules to security groups

### ISSUE THREAD

**Issue by tokiwong** [terraform-aws-modules/terraform-aws-rds-aurora#38]
I have a use case that involves outgoing connections from the aurora rds cluster

I propose an additional resource to `main.tf` like so:
```
resource "aws_security_group_rule" "default_egress" {
  count = "${var.allowed_security_groups_count}"

  type                     = "egress"
  from_port                = "${aws_rds_cluster.this.port}"
  to_port                  = "${aws_rds_cluster.this.port}"
  protocol                 = "tcp"
  source_security_group_id = "${element(var.allowed_security_groups, count.index)}"
  security_group_id        = "${aws_security_group.this.id}"
}
```

**Comment by bryantbiggs** [comment]
hi @tokiwong - because the cluster itself does not initiate outbound connections on its own I would lean towards this addition not fitting well with the module

**Comment by ppihus** [comment]
I'd like to open this again.
There can be a need for egress in case of database replication tasks. In that case, the database does initiate outbound connections.

**Comment by gowthamakanthan** [comment]
> I'd like to open this again. There can be a need for egress in case of database replication tasks. In that case, the database does initiate outbound connections.

I agree with @ppihus, We need to have `egress` for the replication. Could someone please check?
