### ISSUE TITLE
Aurora - I/O Optimized Cluster

### ISSUE THREAD

**Issue by buyukim** [terraform-aws-modules/terraform-aws-rds-aurora#381]
## Is your request related to a new offering from AWS?  Yes

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider...

## Is your request related to a problem? Please describe.
I am frustrated when I have to spend more money than I need to

## Describe the solution you'd like.
AWS recently released  their [Aurora I/O Optimized Cluster](https://aws.amazon.com/blogs/aws/new-amazon-aurora-i-o-optimized-cluster-configuration-with-up-to-40-cost-savings-for-i-o-intensive-applications).  Since it is available via the AWS CLI I would hope we could get this into the TF AWS Provider.

## Describe alternatives you've considered.
Mainly a cost savings measure.  We could try other solutions, such as long-term leasing/purchasing of Provisioned cluster hardware, but those have their own downsides and risks (e.g., lack of scalability)

## Additional context
I understand that maybe this is not the correct usage of your Feature Request, but I would like to emphasize the importance of this new AWS feature to help get it prioritized

**Comment by johnathan99j** [comment]
This is now in the provider ([v4.67.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.67.0)) and can be worked on for the module
(https://github.com/hashicorp/terraform-provider-aws/pull/31336)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.2.0 :tada:
