### ISSUE TITLE
Can't use this module with Terraform AWS provider version 5

### ISSUE THREAD

**Issue by ohmer** [terraform-aws-modules/terraform-aws-rds-aurora#383]
Hi there,

The version constraint prevent using this module with recently released version 5:

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/fa04ae1d361d81d1ea043b89e51ff1ff0bf8ceca/versions.tf#L7

Is there a known incompatibility with version 5?

This was changed in #335 (https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/commit/e054f77c700128c206b0912c51712313981d6fae#diff-dfd5848fa77a04d0343891fe859286cc210473d10f0e62c7f99f0d5ecf1a9927L7) which seems unrelated.

**Comment by bryantbiggs** [comment]
can you provide the details requested in the issue template

**Comment by ohmer** [comment]
my bad, did not read the repo guidelines first.
