### ISSUE TITLE
How do I provision a writer from one instance class and 3 replicas from another instance class.

### ISSUE THREAD

**Issue by ontramatt** [terraform-aws-modules/terraform-aws-rds-aurora#388]
## Description

Thank you the module, it's quite handy.

This is more of a question and/or a documentation request. I've noticed that this module automatically creates 3 db instances in regions where there are availability zones. I have a use case where I want to create a cluster of 4 instances with the writer being a `db.m5d.4xlarge` instance and the 3 read replicas being `db.m5d.large` instances. 

I tried passing several different permutations of the `instances` map but I couldn't figure out how to do this ☝️ 

Is this possible? 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 8.3.0

- Terraform version: 1.2.6

- Provider version(s): 

## Reproduction Code [Required]

Doc request and/or question.

**Comment by bryantbiggs** [comment]
its possible, but this is not how clusters are managed. if you have a failover event, your writer endpoint is going to a reader which in your scenario, will be much smaller than what it was. it is always highly recommended to use a homogeneous set of instances in these clusters

**Comment by ontramatt** [comment]
OK, great. That makes sense, thanks @bryantbiggs. Not sure if it's worth adding a comment to this effect somewhere or a note in the ReadMe but I have an existing (non-Aurora/RDS) cluster which is set up exactly this way: 1 large-ish writer with 3 smaller readers. I will adjust my AWS setup accordingly.

**Comment by ontramatt** [comment]
Reopened for my follow up question ☝️

**Comment by bryantbiggs** [comment]
again, I said its possible but not recommended - especially since you are inquiring about it here. if you wish to learn more, I would suggest diving into the Aurora docs first
