### ISSUE TITLE
Add ability to provide cluster name to an instance instead of cluster arn

### ISSUE THREAD

**Issue by holifieldheights** [terraform-aws-modules/terraform-aws-rds-aurora#390]
## Is your request related to a problem? Please describe.
Unable to use the module to import existing cluster instance due to that instance having the cluster_identifier set as the cluster name and not the arn which this module uses.

## Describe the solution you'd like.
Add an override to allow using the cluster name for the cluster_identifier

**Comment by holifieldheights** [comment]
We're trying to use the module to import a postgres cluster and cluster instances that was initially created through the AWS console.

The cluster imports successfully and we can then manage in code.

However when we import the cluster instances, whilst it allows an import there is a mismatch on the cluster_identifier on any subsequent plans requiring a resource replacement. This mismatch is highlighted below 

    ~ cluster_identifier                    = "cluster-qa" -> "arn:aws:rds:us-east-1:9999999999:cluster:cluster-qa" # forces replacement
    
    This pull request allows us to populate cluster_identifier with the value that the AWS API is passing back, upon our tests we just pass in the cluster name and then it no longer forces a replacement.
    
    
    Hope that makes sense, if not please let me know and I can clarify further :)

**Comment by holifieldheights** [comment]
@bryantbiggs please could we get some feedback on this? 🙏

**Comment by bryantbiggs** [comment]
I haven't had time to look into this but I don't think a module change is required due to importing resources. This sounds like there is an issue with the provider or an issue with how the resource was imported

**Comment by holifieldheights** [comment]
@bryantbiggs thanks for your advice - managed to get to the bottom of it in the end.

Problem was with the terraform import being done with the arn and not just the identifier. When we changed this all lined up

Closing pull request now, thanks anyhow though 🙏
