### ISSUE TITLE
Lifecycle is blocking to recreation of cluster on change of snapshot_identifier value

### ISSUE THREAD

**Issue by vinayabhyankar** [terraform-aws-modules/terraform-aws-rds-aurora#392]
## Description

I am trying to re-create the cluster on the change of snapshot_identifier value. But it simply skipping due to the following code.

lifecycle {
    ignore_changes = [
      # See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#replication_source_identifier
      # Since this is used either in read-replica clusters or global clusters, this should be acceptable to specify
      replication_source_identifier,
      # See docs here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_global_cluster#new-global-cluster-from-existing-db-cluster
      global_cluster_identifier,
      **snapshot_identifier,**
    ]
  }

If possible please remove snapshot_identifier from the lifecycle.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by vinayabhyankar** [comment]
Please ignore this issue for now. I will create a new big with proper description if required

**Comment by umihico** [comment]
I had the same issue, and solved by changing `identifier` too. It trigger their replacements

```terraform
  snapshot_identifier = local.dev_rds_snapshot_identifier
  instances = {
    one = {
      identifier = local.dev_rds_snapshot_identifier
    }
  }
```
