### ISSUE TITLE
Unable to create Aurora postgres serverless with  manage_master_user_password = true

### ISSUE THREAD

**Issue by mkondapalli** [terraform-aws-modules/terraform-aws-rds-aurora#394]
## Description

We upgraded our module from 7.5.1 to 8.3.1 and we are facing issue creating RDS (Aurora postgres serverless) with   manage_master_user_password = true

Here is the configuration before 

module "rds_aurora_postgresql_serverless" {
  source                      = "terraform-aws-modules/rds-aurora/aws"
  version                     = "~> 7.5.1"
  engine                      = "aurora-postgresql"
  engine_mode            = "serverless"
  random_password_length = 32

Changed to following

1) 
module "rds_aurora_postgresql_serverless" {
  source                      = "terraform-aws-modules/rds-aurora/aws"
  version                     = "~> 8.3.1"
  engine                      = "aurora-postgresql"
  engine_mode                 = "serverless"
  manage_master_user_password = true

│ Error: creating RDS Cluster (tf-zfw8ewu099l5vpyfdgw2qziutj): InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank.       
│       status code: 400, request id: c27b4d2d-5452-471c-b41c-365c8bab7e8e

2) 
module "rds_aurora_postgresql_serverless" {
  source                      = "terraform-aws-modules/rds-aurora/aws"
  version                     = "~> 8.3.1"
  engine                      = "aurora-postgresql"
  engine_mode                 = "serverless"
  manage_master_user_password = true
  master_username = "masterroot"

│ Error: creating RDS Cluster (tf-zfw8ewu099l5vpyfdgw2qziutj): InvalidParameterValue: The parameter ManageMasterUserPassword is not valid for engine mode: serverless.

3) 
module "rds_aurora_postgresql_serverless" {
  source                      = "terraform-aws-modules/rds-aurora/aws"
  version                     = "~> 8.3.1"
  engine                      = "aurora-postgresql"
  engine_mode                 = "serverless"
  manage_master_user_password = true
  master_username = "masterroot"
  master_password = "master-123password"

│ Error: creating RDS Cluster (tf-uzao3wwg2ia7snczbvwnpf09xc): InvalidParameterValue: The parameter ManageMasterUserPassword is not valid for engine mode: serverless.
│       status code: 400, request id: 4eac3bcf-d853-4a46-937b-bf095e9d0ceb

4) 
module "rds_aurora_postgresql_serverless" {
  source                      = "terraform-aws-modules/rds-aurora/aws"
  version                     = "~> 8.3.1"
  engine                      = "aurora-postgresql"
  engine_mode                 = "serverless"
  manage_master_user_password = false
  master_username = "masterroot"
  master_password = "master-123password"

This one works fine 

- [YES ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 8.3.1

- Terraform version: 1.3.7
- Provider version(s): 5.5.0

## Reproduction Code : Provided above

 Yes
 Yes
 provided above

## Expected behavior

RDS cluster needs to be created

## Actual behavior

Unable to create with above errors.

### Terminal Output Screenshot(s)

Errors provided above

## Additional context

Upgrade doesn't work

**Comment by bryantbiggs** [comment]
thats because serverless v1 is not supported https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-secrets-manager.html#rds-secrets-manager-limitations
