### ISSUE TITLE
Support setting `preferred_maintenance_window` on Serverless V1 clusters

### ISSUE THREAD

**Issue by stagha** [terraform-aws-modules/terraform-aws-rds-aurora#395]
## Is your request related to a new offering from AWS?

Yes. It is not clear if the provider needs updating at all. From my cursory look at the provider code, it simply passes the parameters to AWS and lets AWS deal with it.

## Is your request related to a problem? Please describe.

AWS added support for configuring maintenance windows on Serverless V1 clusters in February, as described in [this announcement](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-aurora-serverless-v1-configurable-maintenance-windows/). The `terraform-aws-rds-aurora` module does not pass the `preferred_maintenance_window` argument down to the `aws_rds_cluster` resource if `engine_mode` is `serverless`. 

## Describe the solution you'd like.
It looks like all it takes is a one-line change to remove the conditional [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L77). However, I admit I have not tested the resource directly to verify it works.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 9.0.1 :tada:
