### ISSUE TITLE
Absolute minimum required variables

### ISSUE THREAD

**Issue by mulebm** [terraform-aws-modules/terraform-aws-rds-aurora#397]
## Description

The documentation suggests no variables are required, yet if you try build the module from absolute scratch you need to supply a number of parameters. Is there a list of the minimum parameters needed to configure the module to spin up a bare minimum/basic RDS

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 8.3.1

- Terraform version: 1.5.3

- Provider version(s): v4.67.0

## Reproduction Code [Required]

```
module "rds-aurora-test" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "8.3.1"
  name    = "test"
}
```

terraform init/plan/apply

## Expected behavior

a clean plan with no errors, followed by a successful apply

## Actual behavior

terraform plan - OK
terraform apply - ERROR

### Terminal Output Screenshot(s)

```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "dev"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.rds-aurora-test.aws_rds_cluster.this[0]: Creating...
╷
│ Error: creating RDS Cluster (test): InvalidParameterValue: Engine version not found: oscar/null
│       status code: 400, request id: 5aa40b34-16ea-4d53-89f2-de1794a681ad
│ 
│   with module.rds-aurora-test.aws_rds_cluster.this[0],
│   on .terraform/modules/rds-aurora-test/main.tf line 39, in resource "aws_rds_cluster" "this":
│   39: resource "aws_rds_cluster" "this" {
```

**Comment by antonbabenko** [comment]
No variables are required by default because users may _specify_ ([`create = false`](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master#input_create)) that they don't want to create anything.

Please, always take a look at [examples](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master#examples). We have almost all the features shown there.
