### ISSUE TITLE
Add: db_cluster_tags to outputs.tf

### ISSUE THREAD

**Issue by omerls-pw** [terraform-aws-modules/terraform-aws-rds-aurora#398]
## Is your request related to a problem? Please describe.
I needed to get the `cluster tags` in a nested for_each. 

## Describe the solution you'd like.
I added an output locally that I assume could be helpful for others in the future

## Additional context
add this block to `outputs.tf`

```terraform
output "db_cluster_tags" {
  description = "The tags for the resources"
  value       = try(aws_rds_cluster.this[0].tags, null)
}
```

**Comment by bryantbiggs** [comment]
we don't usually output tags since they are provided as inputs. what is the motivation for needing this as outputs?

**Comment by omerls-pw** [comment]
I created a local module that creates a set of clusters (dev/stg/prod) and to finalize the process, stores the admin credentials in `Secrets Manager`. 
In order to have the same tags for both for the `RDS` and the `secrets` I added the output block. 

```terraform
resource "aws_secretsmanager_secret" "db_secret" {
  for_each    = module.aurora_serverless
  name        = "${each.key}_db_secret"
  description = "Secrets for database ${each.key}"
  tags        = each.value.db_cluster_tags
}

resource "aws_secretsmanager_secret_version" "db_secret_version" {
  for_each = module.aurora_serverless

  secret_id = aws_secretsmanager_secret.db_secret[each.key].id
  secret_string = jsonencode({
    username             = each.value.cluster_master_username
    password             = each.value.cluster_master_password
    port                 = each.value.cluster_port
    read_host            = each.value.cluster_reader_endpoint
    write_host           = each.value.cluster_endpoint
    dbInstanceIdentifier = each.value.cluster_database_name
    engine               = "postgres"
  })
} 
```

I guess I could use the `data` object to get the most of the info, but it IMHO it's both not safe as it goes to the password, and cumbersome, since the data's already there. 
WDYT?

**Comment by bryantbiggs** [comment]
I think you will encounter issues with that approach since you are using `for_each` with computed values (the tags)

**Comment by omerls-pw** [comment]
thanks.
I'll rethink about the proper solution for it.
