### ISSUE TITLE
outputs should include the ARN of the RDS cluster

### ISSUE THREAD

**Issue by shenji** [terraform-aws-modules/terraform-aws-rds-aurora#40]
Currently, the project is returning the resource id, wouldn't it make more sense if it returned the ARN directly? The use case is the same for creating policies but look like returning the ARN is more straight forward.

**Comment by sideshowjay** [comment]
@antonbabenko It looks like this was only applied to the 2.x versions for TF 0.12.   Any chance we could get the similar change applied in a 1.x version for those of us still stuck on Terraform 0.11.x for reasons?
