### ISSUE TITLE
Terraform requires final_snapshot_identifier when skip_final_snapshot is true

### ISSUE THREAD

**Issue by mmoreno43** [terraform-aws-modules/terraform-aws-rds-aurora#409]
## Description

Hello, 

We are running the Aurora RDS module to create a database for us. When we tried to destroy the Terraform code we ran into an issue where skip_final_snapshot is set to false by default. We modified our code so that skip_final_snapshot is true. When running Terraform again we are still getting the same error.

We ran the following commands:
- terraform init
- terraform plan
- terraform apply

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Terraform version:
Terraform v1.5.2
- Provider version(s):
registry.terraform.io/hashicorp/aws v5.20.0

## Reproduction Code [Required]

```hcl
module "cluster" {
  source  = "terraform-aws-modules/rds-aurora/aws"

  name           = "stcs-postgres-cluster"
  availability_zones = ["us-west-2a"]
  engine         = "aurora-postgresql"
  engine_version = "14.6"
  instance_class = "db.r6g.large"
  instances = {
    one = {
        identifier = "postgres-writer-instance-1"
    }
    two = {
        identifier = "postgres-reader-instance-1"
    }
  }

  vpc_id               = data.terraform_remote_state.all.outputs.module_paas_vpc_id
  subnets              = [
    data.terraform_remote_state.all.outputs.module_paas_subnet_01_id,
    data.terraform_remote_state.all.outputs.module_paas_subnet_02_id
   ]

  db_subnet_group_name = "stcs-postgres-subnet-group"
  create_db_subnet_group = true

  security_group_rules = {
    ingress0 = {
      cidr_blocks = ["10.0.0.0/8"]
    }
    ingress1 = {
      cidr_blocks = ["172.20.0.0/16"]
    }
    ingress2 = {
      cidr_blocks = ["192.168.0.0/16"]
    }
  }

  storage_encrypted   = true
  apply_immediately   = true # Apply changes immediately or defer until maint window
  monitoring_interval = 10

  master_username = "admin"
  #master_username = data.vault_generic_secret.rds_creds.data["RDS_POSTGRES_MASTER_USER_NAME"]
  master_password = "admin1234tempwillchange"
  #master_password = data.vault_generic_secret.rds_creds.data["RDS_POSTGRES_MASTER_PASSWORD"]
  manage_master_user_password = false

  enabled_cloudwatch_logs_exports = ["postgresql"]

  skip_final_snapshot = true
  
  tags = {
  }
}
```

Are you using workspaces?
- No

Have you cleared the local cache (see Notice section above)?
- Yes

List steps in order that led up to the issue you encountered
- terraform init
- terraform plan
- terraform apply

## Expected behavior

The expected behavior is that Terraform will destroy the cluster if skip_final_snapshot = true.

## Actual behavior

The actual behavior is that Terraform will does not destroy the cluster if skip_final_snapshot = true.

### Terminal Output Screenshot(s)
![terraform3](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/assets/53852075/aaad138f-cd2e-4bfc-887e-de75b4bbb2a0)

**Comment by bryantbiggs** [comment]
check your error message, its saying that you are not skipping the final snapshot which is why it wants an ID

**Comment by mmoreno43** [comment]
Hello,
I thought I was skipping the final snapshot by providing skip_final_snapshot = true in my code?

**Comment by davidvasandani** [comment]
@bryantbiggs we are running into the same issue. We don't want a final snapshot.
