### ISSUE TITLE
Support for scaling configuration of aurora serverless

### ISSUE THREAD

**Issue by shenji** [terraform-aws-modules/terraform-aws-rds-aurora#41]
Add support for MySQL Servers with an example on how to use scaling configurations

scaling_configuration {
    auto_pause = true
    max_capacity = 256
    min_capacity = 2
    seconds_until_auto_pause = 60
  }

**Comment by csreegn** [comment]
Yes, please add this. I would like to override the default `seconds_until_auto_pause` parameter, as the default is too low for me (300s is too eager to shut down for my taste).

**Comment by antonbabenko** [comment]
@rfvermut added this, and [v1.19.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v1.19.0) has been just released.

**Comment by antonbabenko** [comment]
Reopening this issue as a reminder for myself to make the same feature available for Terraform 0.12 users.

**Comment by antonbabenko** [comment]
For Terraform 0.12 users - [v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.4.0) has been released with this feature available.

Check [examples/serverless](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/841228bf15985311aa77eb2683e5b680b7285b8a/examples/serverless/main.tf#L19-L46) for serverless usage:

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/841228bf15985311aa77eb2683e5b680b7285b8a/examples/serverless/main.tf#L19-L46
