### ISSUE TITLE
InvalidParameterCombination: A MonitoringRoleARN value is required

### ISSUE THREAD

**Issue by vishal-elimu** [terraform-aws-modules/terraform-aws-rds-aurora#412]
## Description

When I try to provision PostgreSQL cluster and instance with engine = "aurora-postgresql" and engine_version = "15.3" and set `create_monitoring_role = false`, `monitoring_interval = 60` and `monitoring_role_arn` is `not given`, terraform plan does not return any errors but terraform apply fails with `Error: creating RDS Cluster (postgres-cluster) Instance (postgres): InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0. status code: 400, request id: b7b49f83-b276-4b00-b591-a16c85c9774d`

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: Version 8.5.0

- Terraform version:
Terraform v1.6.1
- Provider version(s):
Terraform v1.6.1

## Reproduction Code [Required]

- In module .tf file, use below input variables  
- `performance_insights_enabled = true`
- `create_monitoring_role = false`
- `monitoring_interval = 60`
- and do not provide `monitoring_role_arn`

## Expected behavior

- The module documentation states that if create_monitoring_role is set to false, provide monitoring_role_arn, if monitoring_role_arn is NOT provided, terraform plan command should fail and throw an error. 

- It would be nice if input variables (create_monitoring_role and monitoring_role_arn) description, mentions about which variable is required and when.  

## Actual behavior

- terraform plan command did not generate any error, however terraform apply failed with `InvalidParameterCombination: A MonitoringRoleARN value is required` error. 

### Terminal Output Screenshot(s)

`Error: creating RDS Cluster (postgres-cluster) Instance (postgres): InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0. status code: 400, request id: b7b49f83-b276-4b00-b591-a16c85c9774d`

**Comment by vishal-elimu** [comment]
I am not able to remove `stale` label from the issue.

**Comment by bryantbiggs** [comment]
What did you expect to happen? The error message is quite clear from the API 

> InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.

You either need to let the module create the role and pass its ARN, or supply an ARN of an existing role yourself

**Comment by vishal-elimu** [comment]
@bryantbiggs Eventually issue is resolved but what I expect is that terraform plan SHOULD return an error when ARN is NOT provided but it did when I ran terraform apply.

**Comment by vishal-elimu** [comment]
@bryantbiggs Wouldn't it be nice if input variables (create_monitoring_role and monitoring_role_arn) descriptions, mentions about which variable is required and when.
