### ISSUE TITLE
cluster_master_user_secret output not clear

### ISSUE THREAD

**Issue by schammah** [terraform-aws-modules/terraform-aws-rds-aurora#413]
## Description

When enabling `manage_master_user_password = true`
output for that is weird, instead of getting a map with 3 key:values, it output something with the function `tolist`

I'm calling the module multiple time , one for each DB, other outputs are working fine

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `8.5.0`

- Terraform version: `1.6.3`
- Provider version(s): `5.24.0`

## Reproduction Code [Required]

This is the code for my outputs (one regular and one for master_user_secret)

```
output "cluster_endpoint" {
  value       = { for key, module in module.aurora : key => module.cluster_endpoint }
  description = "Writer endpoint for the cluster"
}

output "cluster_master_user_secret" {
  value       = { for key, module in module.aurora : key => module.cluster_master_user_secret }
  description = "The generated database master user secret when `manage_master_user_password` is set to `true`"
}
```

## Actual behavior

here's the outputs i am getting:

```
cluster_endpoint = {
  "admin" = "admin-aurora-mysql-db-c-usea1.cluster-xxxxxxxxxxx.us-east-1.rds.amazonaws.com"
  "app" = "app-aurora-mysql-db-c-usea1.cluster-xxxxxxxxxxx.us-east-1.rds.amazonaws.com"
}
cluster_master_user_secret = {
  "admin" = tolist([
    {
      "kms_key_id" = "arn:aws:kms:us-east-1:xxxxxxxxxxx:key/ddf52ac8-47f4-46fa-bfe3-0dcxxxxxxxxx"
      "secret_arn" = "arn:aws:secretsmanager:us-east-1:xxxxxxxxxxx:secret:rds!cluster-0c256ee8-66dc-4ef3-85f8-523exxxxxxxxxxxxx"
      "secret_status" = "active"
    },
  ])
  "app" = tolist([
    {
      "kms_key_id" = "arn:aws:kms:us-east-1:xxxxxxxxxxx:key/ddf52ac8-47f4-46fa-bfe3-0dxxxxxxxxxxxx"
      "secret_arn" = "arn:aws:secretsmanager:us-east-1:xxxxxxxxxxx:secret:rds!cluster-d840afb3-0b1a-4eaa-a4c8-e9d8xxxxxxxxxxx-xxxxxxxxx"
      "secret_status" = "active"
    },
  ])
}
```

## Additional context

Not sure if this actually because of terraform's provider and not the module, 
Would appreciate assistance if it stays like this how to refer for the "Secret_arn" key lets say in 1 of the elements

Thank you

**Comment by bryantbiggs** [comment]
we are simply passing through the output so this is coming from the provider spec. you can access to values as you see fit - using keys for maps or indexes for lists
