### ISSUE TITLE
upgrade module from 7.x to 8.x

### ISSUE THREAD

**Issue by xyfleet** [terraform-aws-modules/terraform-aws-rds-aurora#414]
## Description

Do I have to upgrade aurora mysql engine version from 5.7 to 8.X when I try to upgrade the rds-aurora module from 7.X to 8.X? (Upgrading engine version to 8.X from 5.7 will be more complicated than upgrading the module.)

Can I ONLY upgrade rds module? 

## Versions

- Module version [Required]:
current rds module: 7.6.0

- Terraform version:
Terraform v1.5.6
- Provider version(s):
aws: 5.24.0

**Comment by bryantbiggs** [comment]
The engine version is separate from the module version - they are not interconnected
