### ISSUE TITLE
Multi AZ

### ISSUE THREAD

**Issue by devasivaram** [terraform-aws-modules/terraform-aws-rds-aurora#421]
Hi, I have been using this module for a long time, but now I have a requirement to create RDS Aurora Postgresql with Multi-AZ. I have tried a lot to make modifications or use another module. If possible could you please create an Multi AZ RDS Aurora Postgresql terraform code?

**Comment by bryantbiggs** [comment]
Aurora is multi-az by default https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraHighAvailability.html

**Comment by devasivaram** [comment]
But I can choose the multi az enable option while creating it from the console, but via Terraform creation when I check the configuration it shows multi az as no. Even I have tried to add 2 instances as well the configuration status of multi az shows no while created by Terraform, but from console, it will show Yes.

**Comment by ahummel25** [comment]
@devasivaram @bryantbiggs It seems like the option to place additional instances of your Aurora cluster in separate AZs is not an option here. So Aurora itself might be Multi AZ compatible by default, but with this module, the cluster instances can only reside in a single AZ and cannot be scattered across AZs?

**Comment by bryantbiggs** [comment]
> the cluster instances can only reside in a single AZ and cannot be scattered across AZs

Thats not true

**Comment by ahummel25** [comment]
I stand corrected. All depends on how you configure the `instances` config. Works fine with more than one instance.
