### ISSUE TITLE
lifecycle option for cluster_instance

### ISSUE THREAD

**Issue by Souher0** [terraform-aws-modules/terraform-aws-rds-aurora#422]
## Is your request related to a problem? Please describe.

I want to be able to add the lifecycle behavior below to increase db instance deletion protection:
lifecycle {
    prevent_destroy = true
  }
## Describe the solution you'd like.

Lifecycle variable added

**Comment by bryantbiggs** [comment]
That's not going to be possible, lifecycle blocks do not support variables and we can't force that on everyone. You'll need to protect your Terraform provisioning process instead

**Comment by Souher0** [comment]
Understandable, thanks for the reply
