### ISSUE TITLE
Variables.tf file

### ISSUE THREAD

**Issue by lcdiaz2106** [terraform-aws-modules/terraform-aws-rds-aurora#423]
Hello
I would like to use this code as I have to create resource "aws_rds_global_cluster" 
But, I see that your variables.tf file is empty... Do you have some file with the variables somewhere?
Let me know

Many thanks

**Comment by bryantbiggs** [comment]
not sure what you are seeing, but its not empty https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/7bf5933100eb355b13854232e5d63c62ea7cad35/variables.tf#L1-L719

**Comment by lcdiaz2106** [comment]
Hoo sorry
yes now I can see the variables.
Sorry for this :)
Many thanks
