### ISSUE TITLE
The removal of support for master password generation was maybe too hasty.

### ISSUE THREAD

**Issue by theherk** [terraform-aws-modules/terraform-aws-rds-aurora#428]
## Is your request related to a problem? Please describe.
Not using master password, where support for management within Secrets Manager is available makes good sense, and should be the default. But the removal of the ability to generate a master password in some cases, seems not to take into account that the Secrets Manager integration is not available in all cases. For example, see [Limitations for Secrets Manager integration with Amazon Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-secrets-manager.html#rds-secrets-manager-limitations). One such example is:

> DB clusters that are part of an Aurora global database

In those cases, we still need to provide a password. We can of course generate one in the block that implements the module, but it makes sense to still provide it here.

## Describe the solution you'd like.
Provide the feature as it was before.

## Describe alternatives you've considered.
As mentioned above, the alternative required currently is to generate the password outside the module, which is fine, but it would be a quality of life improvement as it was before to provide it in the module.

Another alternative is to rely on IAM authentication for the cluster, but I'm not entirely sure the implications of this in a global cluster (need to do some testing).

**Comment by bryantbiggs** [comment]
> Provide the feature as it was before

You really should look for ways to avoid having the password in plaintext in your statefile. We do not have any plans to re-enable that functionality because its a really poor practice

That said, there is nothing from stopping you from using the random password resource yourself to generate a password and pass it into this module - we want to push users towards the recommended approach (for their own benefit)

**Comment by theherk** [comment]
Of course one should avoid that. I thought I made it clear I agree with the intent. The only issue is with the stated removal being:

> With RDS now supporting the [integration with SecretsManager to manage the master user password](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager/), the ability to generate a random password has been removed from this module

But RDS doesn't support that in all cases. In those cases, what is your recommendation? I cannot enable IAM authentication without setting a master password. So, without encrypted state support, I'm not clear on the recommended approach here.

**Comment by bryantbiggs** [comment]
If you don't want to go the managed password route, just supply a password as input to your module via `master_password`. You can even use the random resource like this module previously did if you'd like https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/bf4d92cbf0ff66987eec9dd0fcff66e9b2ae158b/main.tf#L26-L31

```hcl
  # ...
  manage_master_user_password = false
  master_password = <something>
  # ...
```

**Comment by theherk** [comment]
I appreciate you taking the time. Just to clarify, that is precisely what I am doing. I mention that as the alternatives in the opening remarks. I guess my question is, if this is a poor practice, what is the alternative? I do want to go the managed password route; it just isn't supported.
