### ISSUE TITLE
Autoscaling does not scale cluster to min capacity on creation

### ISSUE THREAD

**Issue by Neifn** [terraform-aws-modules/terraform-aws-rds-aurora#432]
## Description

When creating a cluster with autoscaling enabled, cluster is not automatically scaled to `autoscaling_min_capacity` value and remains stuck with directly created instances. 
- [✅] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 9.0.0

- Terraform version:
1.7.2
- Provider version(s):
5.35.0

## Reproduction Code [Required]
```
module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "9.0.0"

  name  = "test-aurora"

  engine         = "aurora-mysql"
  engine_version = "5.7.mysql_aurora.2.11.4"
  instance_class = "db.t3.medium"

  port    = 3306
  vpc_id  = module.vpc.vpc_id
  subnets = module.vpc-subnets.subnet_ids

  master_username                     = "admin"
  manage_master_user_password         = true
  iam_database_authentication_enabled = true

  instances                = { primary = {} }
  autoscaling_enabled      = true
  autoscaling_min_capacity = 2
  autoscaling_max_capacity = 3


  allow_major_version_upgrade = true
  apply_immediately           = true
  copy_tags_to_snapshot       = true
  skip_final_snapshot         = true
}
```

`terraform apply`

## Expected behavior
Reader nodes are scaled to the minimum capacity when cluster becomes available. 

## Actual behavior
Cluster will be created with only one instance. Autoscaling configuration will not add any reader nodes.

## Additional context
If you set `autoscaling_enabled` to `false` and create `aws_appautoscaling_target` and `aws_appautoscaling_policy` outside the module with `depends_on` set to whole module reader nodes are created as expected.

**Comment by NeoMopp** [comment]
We have encountered the same issue recently, and found that the auto scaling policy is created, but seems to be inactive. By modifying the autoscaling policy, simply editing and saving, the auto scaler kicks in and creates the desired minimum instances.

**Comment by bryantbiggs** [comment]
this appears to be related to an upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/31329

**Comment by Neifn** [comment]
Issue still persists in newer module versions
