### ISSUE TITLE
Typo in repo About section

### ISSUE THREAD

**Issue by johnathan99j** [terraform-aws-modules/terraform-aws-rds-aurora#436]
The About section of the repo has 2 T's at the front and this filters through to the registry page as well

![image](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/assets/15066398/72272ade-f05e-4b8a-9698-31fc10e26f9e)

![image](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/assets/15066398/380058fd-9899-411d-9a96-a90e1a5b9757)

**Comment by bryantbiggs** [comment]
fixed - thank you!
