### ISSUE TITLE
Error when creating role in China

### ISSUE THREAD

**Issue by stephenrjohnson** [terraform-aws-modules/terraform-aws-rds-aurora#437]
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blame/ec99016a364fe7abee822f78a11b8ccfccaa70d9/main.tf#L240

Error:
`
│ Error: creating IAM Role (terraform-20240314084919599800000001): MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"monitoring.rds.amazonaws.com.cn"
│       status code: 400, request id: 607f6a7e-6557-4b0d-90d3-822172f306c4
│ 
│   with module.rds.module.rds_cluster.aws_iam_role.rds_enhanced_monitoring[0],
│   on .terraform/modules/rds.rds_cluster/main.tf line 245, in resource "aws_iam_role" "rds_enhanced_monitoring":
│  245: resource "aws_iam_role" "rds_enhanced_monitoring" {
`

On opening a role that works in China it's 
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "monitoring.rds.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
`

So it seems to me in china the suffix should be .com for ht service, unless I'm missing something. Can anyone else confirm this is the case?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 9.3.1 :tada:
