### ISSUE TITLE
terraform-aws-rds-aurora module should allow list of databases to be created in postgres instance/cluster

### ISSUE THREAD

**Issue by aniketsharad** [terraform-aws-modules/terraform-aws-rds-aurora#439]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑
  
## Is your request related to a problem? Please describe.
Cannot create multiple databases in the same aurora postrges instance. 
input [database_name](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora?tab=readme-ov-file#input_database_name) variable does not accepts a list. 

## Describe the solution you'd like.
input variable [database_name](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/variables.tf#L105) should accept list and allow for the user to create multiple databases.

## Describe alternatives you've considered.
Some alternatives will be to run postgres client in the same VPC where we are hosting this postgres and run commands to crated postgres database, but that will require some additional code and require us to host postgres client in the same network

**Comment by bryantbiggs** [comment]
I would suggest investing some time digging into the AWS docs and APIs on this - its not something we, nor the AWS provider control
