### ISSUE TITLE
Support custom ignore_change

### ISSUE THREAD

**Issue by aidendou** [terraform-aws-modules/terraform-aws-rds-aurora#445]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Yes https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

## Is your request related to a problem? Please describe.

currently, there is no way to config what changes can be ignored by using rds_aurora module, such as master_password, database_name, etc.

## Describe the solution you'd like.

Would like to have the ability to merge a list of variables into the default ignore_changes list.

## Describe alternatives you've considered.

seems no obvious alternatives.

**Comment by bryantbiggs** [comment]
Terraform core does not support this

**Comment by aidendou** [comment]
> Terraform core does not support this

do you mind elaborate a bit? not a TF expert, but I don't see why it wouldn't work.

**Comment by bryantbiggs** [comment]
Terraform does not support variables within lifecycle blocks - they have to be defined statically

**Comment by aidendou** [comment]
thank you. I found the document. will close this.

**Comment by aidendou** [comment]
@bryantbiggs any thoughts on adding "master_password" as a static value in the ignore_changes block?

**Comment by bryantbiggs** [comment]
What would be the motivation for that?

**Comment by aidendou** [comment]
we don't want to use secret manager, also can't set plain text in tf file, and to prevent TF reset master_password

**Comment by bryantbiggs** [comment]
Ah, ok. Letting RDS manage this is the recommendation which means no changes to the current codebase
