### ISSUE TITLE
Add lifecyle ignore changes on AZs to aws_rds_cluster resource 

### ISSUE THREAD

**Issue by AkramDhiabi** [terraform-aws-modules/terraform-aws-rds-aurora#446]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅:  aws version : `5.42`

## Is your request related to a problem? Please describe.
RDS automatically assigns 3 AZs if less than 3 AZs are configured, which will show as a difference requiring resource recreation next Terraform apply
## Describe the solution you'd like.
I'm requesting an update to our RDS cluster Aurora module to include a lifecycle block with the ignore_changes configuration for the availability_zones argument. This change is necessary to address the following issue:

- When specifying fewer than three availability zones (AZs), RDS automatically assigns three AZs, which Terraform interprets as a configuration change requiring resource recreation during subsequent plans.
- Resource recreation leads to downtime, which we want to avoid.

By adding the lifecycle block to ignore changes in availability_zones, we can maintain consistency in our configuration and avoid unnecessary resource recreation and downtime.

## Describe alternatives you've considered.
Here is the code snippet to add [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/39146d54a888dee11dc00706e40f1964236394f0/main.tf#L160):

```
lifecycle {
  ignore_changes = [
    "availability_zones"
  ]
}

```
## Additional context
N/A

**Comment by bryantbiggs** [comment]
I don't see a valid reason to ignore this - the API is clear in that its a replace operation when the value has changed https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-availabilityzones
