### ISSUE TITLE
Blue geen deployment in terraform

### ISSUE THREAD

**Issue by abhikapstan** [terraform-aws-modules/terraform-aws-rds-aurora#451]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

i can see that aws rds module has blue green deployment option but this module does not have that can we add this a feature

**Comment by bryantbiggs** [comment]
Does RDS Aurora support blue/green? Does the AWS Terraform provider support blue/green for RDS Aurora?

**Comment by en-smihailuta** [comment]
@bryantbiggs there is an option in RDS module https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest?tab=inputs "blue_green_update"

**Comment by bryantbiggs** [comment]
That is RDS - this is RDS Aurora. They are two separate services and APIs

**Comment by toneill818** [comment]
@bryantbiggs Aurora does support blue green deployments and it looks like the provider does too. 
https://aws.amazon.com/blogs/aws/new-fully-managed-blue-green-deployments-in-amazon-aurora-and-amazon-rds/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#blue_green_update

**Comment by bryantbiggs** [comment]
@toneill818 again - that is a link to an RDS instance resource which is not Aurora

Our RDS module does support this since RDS instances support this https://github.com/terraform-aws-modules/terraform-aws-rds/blob/a4ae4a51545f5cb617d30b716f6bf11840c76a0e/main.tf#L115

**Comment by luodonghua** [comment]
Is there any timeline to support this feature for Aurora module? Since RDS module already has this supported

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/28956#issuecomment-1826174309
