### ISSUE TITLE
Auto minor version upgrade & ignore changes

### ISSUE THREAD

**Issue by el-capitan-insait** [terraform-aws-modules/terraform-aws-rds-aurora#454]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Yes - ignore_changes

## Is your request related to a problem? Please describe.

I'm setting [auto_minor_version_upgrade] and the DB had been upgrade .
now the next time I'm the TF it notice the change and want to rollback ...

## Describe the solution you'd like.

if [auto_minor_version_upgrade] the version should be not trigger an update

```
lifecycle {
    ignore_changes = [
      engine_version,
    ]
  }
```

## Describe alternatives you've considered.

Right now I'm updating the module var to reflect the new version

**Comment by gayashankgithub** [comment]
I have a similar issue. with `auto_minor_version_upgrade` set to `true` TF tries to revert from PostgreSQL (for example) 13.14 to 13.12.  (DB is created using 13.12 originally and minor version upgrade has gone through) 

I've read couple of [updates](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/286) related to this issue. Seems like the `engine_version` is not a mandatory argument anymore. Anyway when using PostgreSQL, (suggested)[https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/286#issuecomment-1456380420] methods by @bryantbiggs doesn't seems to work.

I'm using below versions. 
```
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.55.0"
    }
    
 ----
 module "postgres_aurora_serverless" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "7.6.2"
  
 ```
  
  Also noticed that when using a module there's a limitation to use `lifecycle`
  
  ```
  lifecycle {
    ignore_changes = [
      engine_version,
    ]
  }
  ```

**Comment by bryantbiggs** [comment]
issues without reproductions will be ignored - we simply are unable to help troubleshoot without seeing what values are being set and being able to interact with a repro

**Comment by bryantbiggs** [comment]
you link to where I said to not fully specify the version since it will conflict with the auto minor upgrade, yet you are doing exactly that https://github.com/gayashankgithub/rds-version-testing/blob/bc0ca76b826833bf910c359afc8c771b0fb54a78/infrastructure/main.tf#L3 

Do not do that and the issue should be resolved

**Comment by gayashankgithub** [comment]
Thank you for the update. 

In my use case, as I explained the database is already created with version'13.12'. 

And in 7th step I have tried giving only the major version '13' as same as your explanation. 

Since the initial configuration is created with 13.12 and aws has upgraded to 13.13, I cannot set it to '13'. See above error.

**Comment by gayashankgithub** [comment]
Thank you for the update.

Correct me if I'm wrong in the example provided the version is not fully specified when creating the resources allowing version upgrades to happen and not conflict in future.  

But In my use case (which I believe is the same as the reported issue), **I already have a PostgreSQL database created with version 13.12** (created a couple of months ago), which has been auto-updated.
After some time when running Terraform again it cannot figure out what to do with the updated version.

Also below are the steps I tried to get the state updated to the new version and run it with 13. 

1. Get the state update with terraform refresh
`terraform apply --refresh-only  -no-color -var-file="qa/qa.tfvars"`

2. Check updated version in the state. Check the engine_version and engine_version_actual
```console
terraform state  show 'module.postgres_aurora_serverless.aws_rds_cluster_instance.this["one"]'
# module.postgres_aurora_serverless.aws_rds_cluster_instance.this["one"]:
resource "aws_rds_cluster_instance" "this" {
    arn                                   = "arn:aws:rds::db:test-rds-versioning-test-one"
    auto_minor_version_upgrade            = true
    availability_zone                     = "us-east-1b"
    
    engine                                = "aurora-postgresql"
    engine_version                        = "13.13"
    engine_version_actual                 = "13.13"

}
```

3. Change engine_version on the configuration file

https://github.com/gayashankgithub/rds-version-testing/blob/new-branch-1/infrastructure/main.tf#L3

```hcl
locals {
  engine    = "aurora-postgresql"
  version   = "13"
}

```

4. Apply terraform.

```console
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.postgres_aurora_serverless.aws_rds_cluster.this[0] will be updated in-place
  ~ resource "aws_rds_cluster" "this" {
      ~ engine_version                        = "13.13" -> "13"
        id                                    = "test-rds-versioning-test"
        tags                                  = {}
        # (43 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.postgres_aurora_serverless.aws_rds_cluster_instance.this["one"] will be updated in-place
  ~ resource "aws_rds_cluster_instance" "this" {
      ~ engine_version                        = "13.13" -> "13"
        id                                    = "test-rds-versioning-test-one"
        tags                                  = {}
        # (27 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.postgres_aurora_serverless.aws_rds_cluster_instance.this["two"] will be updated in-place
  ~ resource "aws_rds_cluster_instance" "this" {
      ~ engine_version                        = "13.13" -> "13"
        id                                    = "test-rds-versioning-test-two"
        tags                                  = {}
        # (27 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.postgres_aurora_serverless.aws_rds_cluster.this[0]: Modifying... [id=test-rds-versioning-test]

Error: updating RDS Cluster (test-rds-versioning-test): operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 0d470073-267b-4c1f-bd6c-b4dbd2ff1e66, api error InvalidParameterCombination: Cannot upgrade aurora-postgresql from 13.13 to 13.12

  with module.postgres_aurora_serverless.aws_rds_cluster.this[0],
  on .terraform/modules/postgres_aurora_serverless/main.tf line 61, in resource "aws_rds_cluster" "this":
  61: resource "aws_rds_cluster" "this" {

Releasing state lock. This may take a few moments...
```

**Comment by bryantbiggs** [comment]
if you are telling RDS to auto upgrade the minor version, then you should not specify the minor version for the engine - you only specify the major version and from then on, RDS will automatically upgrade it for you

But the fact still remains that we are not going to ignore the engine version in this module - there are users that want to set the full version and have strict control over the version through Terraform. It is up to you to get your code and infra aligned so that they work together, we cannot do that here fore you
