### ISSUE TITLE
Can't disable automatic password rotation when AWS manages database secret

### ISSUE THREAD

**Issue by manuela-loka** [terraform-aws-modules/terraform-aws-rds-aurora#457]
## Description

When a new aurora database is created, and `manage_master_user_password = true`, the behavior is that, the created secret has a rotation rule that is executed by default after 7 days even though `manage_master_user_password_rotation = false`, and this cannot be managed or disabled at first deployment of the database. The only way I found was to enable the rotation with mock values, and then disable it back.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 9.4.0

- Terraform version: v1.9.1
- Provider version(s): v5.57.0

## Reproduction Code

```
module "rds-aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "9.4.0"

  name           = "test-db"
  engine         = "aurora-postgresql"
  engine_version = "15.4"
  instance_class = "db.t3.medium"
  instances = {
    one = {}
  }
  vpc_id                 = module.vpc.vpc_id
  create_db_subnet_group = true
  subnets                = module.vpc.public_subnets
  storage_encrypted               = true
  manage_master_user_password     = true
  master_username                 = "master"
  enabled_cloudwatch_logs_exports = ["postgresql"]
  create_cloudwatch_log_group     = true
  manage_master_user_password_rotation = false
}
```

- terraform apply

## Expected behavior

The created secret has rotation disabled

## Actual behavior

The created secret has a rotation that occurs after 7 days

## Additional info
There is a similar issue on RDS module which was fixed, hopefully it can also be for this module -> https://github.com/terraform-aws-modules/terraform-aws-rds/issues/538

**Comment by bryantbiggs** [comment]
the issue you linked was not "fixed" - the answer is that this is the nature of using this feature by the RDS API https://github.com/terraform-aws-modules/terraform-aws-rds/issues/538#issuecomment-1965606613
