### ISSUE TITLE
 InvalidParameterValue: The parameter ManageMasterUserPassword is not valid for engine mode: serverless

### ISSUE THREAD

**Issue by rachlenko** [terraform-aws-modules/terraform-aws-rds-aurora#460]
## Description
Module : "aurora_postgresql" 
The functionality of using a previously generated password does not seem to work 

## Versions
- Provider version(s):

- Module version 
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/random...
- Finding cloudposse/utils versions matching ">= 0.12.0"...
- Finding hashicorp/helm versions matching ">= 2.0.0, >= 2.5.1, 2.12.1"...
- Finding hashicorp/tls versions matching ">= 3.0.0"...
- Finding hashicorp/time versions matching ">= 0.9.0"...
- Finding hashicorp/cloudinit versions matching ">= 2.0.0"...
- Finding gavinbunney/kubectl versions matching ">= 1.14.0"...
- Finding hashicorp/null versions matching ">= 3.0.0"...
- Finding hashicorp/kubernetes versions matching ">= 2.10.0, 2.16.0"...
- Finding oboukili/argocd versions matching ">= 3.0.1, 6.0.3"...
- Finding hashicorp/aws versions matching ">= 2.53.0, >= 3.0.0, >= 3.28.0, >= 3.35.0, >= 3.72.0, >= 4.0.0, >= 4.2.0, >= 4.9.0, >= 4.35.0, >= 4.47.0, >= 4.57.0, >= 5.0.0, >= 5.21.0, >= 5.59.0"...
- Installing hashicorp/tls v4.0.5...
- Installed hashicorp/tls v4.0.5 (signed by HashiCorp)
- Installing hashicorp/cloudinit v2.3.4...
- Installed hashicorp/cloudinit v2.3.4 (signed by HashiCorp)
- Installing gavinbunney/kubectl v1.14.0...
- Installed gavinbunney/kubectl v1.14.0 (self-signed, key ID AD64217B5ADD572F)
- Installing hashicorp/kubernetes v2.16.0...
- Installed hashicorp/kubernetes v2.16.0 (signed by HashiCorp)
- Installing hashicorp/random v3.6.2...
- Installed hashicorp/random v3.6.2 (signed by HashiCorp)
- Installing cloudposse/utils v1.24.0...
- Installed cloudposse/utils v1.24.0 (self-signed, key ID 7B22D099488F3D11)
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
- Installing oboukili/argocd v6.0.3...
- Installed oboukili/argocd v6.0.3 (self-signed, key ID 09A6EABF546E8638)
- Installing hashicorp/aws v5.59.0...
- Installed hashicorp/aws v5.59.0 (signed by HashiCorp)
- Installing hashicorp/helm v2.12.1...
- Installed hashicorp/helm v2.12.1 (signed by HashiCorp)
- Installing hashicorp/time v0.12.0...
- Installed hashicorp/time v0.12.0 (signed by HashiCorp)

1.9.2, 1.6

## Reproduction Code [Required]

data "aws_rds_engine_version" "postgresql" {
  engine  = "aurora-postgresql"
  version = "14.9"
}

resource "random_password" "master" {
  length  = 20
  special = false
}

module "aurora_postgresql" {
  source            = "terraform-aws-modules/rds-aurora/aws"
  count             = 1
  name              = "clusterNamePostgresql"   
  engine            = data.aws_rds_engine_version.postgresql.engine  
  engine_mode       = "serverless"
  storage_encrypted = true
  master_username   = "root"

  vpc_id               = var.postgresql_spec.vpc_id
  db_subnet_group_name = "subnet-test"
  security_group_rules = {
    vpc_ingress = {
      from_port   = 5432
      to_port     = 5432
      protocol    = "tcp"
      cidr_blocks = module.vpc.private_subnets_cidr_blocks
      description = "Allow PostgreSQL traffic"
    }
  }

  master_password = random_password.master.result

  monitoring_interval = 30

  #preferred_maintenance_window = local.v2_preferred_maintenance_window 
  skip_final_snapshot = false

  scaling_configuration = {

    auto_pause               = false
    min_capacity             = 4
    max_capacity             = 32
    seconds_until_auto_pause = 600
    timeout_action           = "RollbackCapacityChange"

    tags = ""
  }
}

terraform init 
terraform plan 
terraform apply 

## Expected behavior

 I attempted to install an RDS serverless cluster
using a previously generated password for the master user

### Terminal Output Screenshot(s)

I used the example with aurora_postgresql and got the following errors: 

│ Error: creating RDS Cluster (aurora-postgresql-test): InvalidParameterValue: The parameter ManageMasterUserPassword is not valid for engine mode: serverless.
│ 	status code: 400, request id: c2ae05e3-71a3-4296-88ba-5c793fd898e9
│ 
│   with module.test.module.aurora_postgresql[0].aws_rds_cluster.this[0],
│   on .terraform/modules/test.aurora_postgresql/main.tf line 39, in resource "aws_rds_cluster" "this":
│   39: resource "aws_rds_cluster" "this" {

**Comment by magreenbaum** [comment]
You will want to set `manage_master_user_password = false`. Example [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/401023134a0487a78e0d5a122dfb33f2d0bbab53/examples/serverless/main.tf#L43-L45).
