### ISSUE TITLE
deleting parameter group failed

### ISSUE THREAD

**Issue by FlorinAndrei** [terraform-aws-modules/terraform-aws-rds-aurora#466]
It appears that changing these options...

```
create_db_cluster_parameter_group = true
create_db_parameter_group = true
```

...from true to false and trying to apply the change results in an error saying:

```
Error: deleting RDS DB Parameter Group (app-main): operation error RDS: DeleteDBParameterGroup, https response error StatusCode: 400, RequestID: 8e340d2b-295f-4ff1-9094-519535dd2bc1, InvalidDBParameterGroupState: One or more database instances are still members of this parameter group app-main, so the group cannot be deleted
```

opentofu-1.8.1
terragrunt-0.67.1
aws-provider-5.66.0

The workaround was to manually detach the parameter groups from the instances and from the cluster, and then re-run plan and apply.

Perhaps the module should detach the groups before deleting them?

Current inputs provided by Terragrunt to OpenTofu:

[inputs.txt](https://github.com/user-attachments/files/16901326/inputs.txt)

I can provide more complete code if needed.

**Comment by bryantbiggs** [comment]
you cannot delete a parameter group that is in use. if you wish to delete it, you will first need to switch your cluster(s) to use a different parameter group, and then you can proceed to delete it once NO clusters are using it

**Comment by FlorinAndrei** [comment]
> you cannot delete a parameter group that is in use

@bryantbiggs I agree with that statement.

However, this was a parameter group managed by this module. It is a reasonable expectation that a module could seamlessly handle the resources it has created, and would not throw an error if you merely flip a config switch within the module.

If that was a parameter group created externally (not by this module), then I would agree that it is the user's responsibility to handle the transition.

**Comment by bryantbiggs** [comment]
It can handle that resource, but it can't delete something that its currently relying on. You have to give it a replacement that it will need to use so that it can delete the parameter group that it created and is currently using. This is not a module level issue - this is just how the RDS Aurora API works in general
