### ISSUE TITLE
Password rotation enabled with `master_password`

### ISSUE THREAD

**Issue by nmittler** [terraform-aws-modules/terraform-aws-rds-aurora#469]
## Description

I had originally configured the aurora TF module with `manage_master_user_password=true`. Inspection in AWS console, showed that rotation was enabled regardless of the value of `manage_master_user_password`. So the first issue is that this behavior contradicts the docs, which say:

```
manage_master_user_password_rotation bool
Description: Whether to manage the master user password rotation. Setting this value to false after previously having been set to true will disable automatic rotation.
```

This issue seems to have been captured by https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/457, although no action was taken to update the docs. We should probably do that.

I then decided to go with a manual password and avoid the "managed" stuff altogether. I unset `manage_master_user_password` and instead set `master_password` directly. Going back to AWS console, I still see that the secret is configured for rotation.

I then deleted my aurora cluster and the secret manually in AWS console and then re-applied the terraform. Same problem.

I then manually disabled the password rotation in AWS console and re-applied the terraform. Terraform showed no changes, so it appears it's not even looking at this value on the secret.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.8.5
- Provider version(s):
Terraform v1.8.5
## Reproduction Code [Required]

NOTE: I did the following from a clean account with no terraform cache.

1. Create an aurora module configured for serverless v2 with `master_password` set.

## Expected behavior

The RDS secret in AWS console should match the generated password and have auto-rotation disabled.

## Actual behavior

The RDS secret in AWS console does not match the generated password and has auto-rotation enabled.

This seems to imply that the `master_password` if completely ignored by the module.

**Comment by nmittler** [comment]
I tore down my environment again and re-created it with `manage_master_user_password` explicitly set to `false`. No automatic secret was created by RDS. Closing this.

**Comment by mschultz-aofl** [comment]
Adding this here: This is an issue with the upstream provider, see https://github.com/hashicorp/terraform-provider-aws/issues/33462 - I also experienced this and boy was it not fun dealing with the 2am war room call.
