### ISSUE TITLE
aurora cluster different size

### ISSUE THREAD

**Issue by uje-m** [terraform-aws-modules/terraform-aws-rds-aurora#54]
I want to make RDS Aurora Cluster with 1 read replica,
is it possible to set the replica with different size using this module?

**Comment by max-rocket-internet** [comment]
There is no "read replicas" in Aurora. There is only cluster instances and they can be either readers or writers. And they must all be the same instance type.

So, no 🙂

**Comment by uje-m** [comment]
> There is no "read replicas" in Aurora. There is only cluster instances and they can be either readers or writers. And they must all be the same instance type.
> 
> So, no 🙂

Sorry, I mean reader.

from the console we could change the reader’s or the writer's instance type.
I thought we could specify each instance type.

**Comment by max-rocket-internet** [comment]
> I thought we could specify each instance type.

Sorry, yes you can, but currently not possible with this module.

**Comment by bryantbiggs** [comment]
closed with #146
