### ISSUE TITLE
Aurora Backtrack Mysql

### ISSUE THREAD

**Issue by uje-m** [terraform-aws-modules/terraform-aws-rds-aurora#55]
HI,

is this module support backtrack on aurora mysql(5.6) ?

I got this error:
"Error: module "db_ecomm_mysql": "backtrack_window" is not a valid argument"

**Comment by antonbabenko** [comment]
For Terraform 0.12 users - [v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.4.0) has been released with this feature available.
