### ISSUE TITLE
variable names

### ISSUE THREAD

**Issue by jlorieau** [terraform-aws-modules/terraform-aws-rds-aurora#56]
The variable names and descriptions are a bit confusing in some cases:

1. ``skip_final_snapshot``. If True, then no snapshot will be taken when the cluster is destroyed. However, the description states "Should a final snapshot be created on cluster destroy," which if true, would mean that a final snapshot will be created. (the opposite) Something like "Skip the creation of a final snapshot on cluster destruction" would align with the variable name.
2. The variable names, like ``db_name``/``name `` ``subnets``/``subnet_ids``, are not consistent between your terraform-aws-rds and terraform-aws-rds-aurora modules. It would be helpful to have consistent variable names and descriptions for the same variables across your modules.

Thanks for the helpful modules!

J

**Comment by jlorieau** [comment]
``replica_count`` is another variable I find confusing. 

According to the "aws_rds_cluster_instance" resource, count amounts to the number of instances created in the cluster. I interpret this to mean that a count of 1 would create 1 master and 0 slaves (replicas) and a count of 2 would be 1 master and 1 slave (replica). If that is indeed the case, wouldn't ``replica_count``=count - 1, instead of =count? (conversely, count = 1 + replica_count)

**Comment by scottx611x** [comment]
This took me for a loop today as well ☝️

**Comment by bondezbond** [comment]
yeah I agree. I find this confusing as well cause of how the description is worded. I would try to make it little clearer that the replica_count is including the master hence why its min 1.
