### ISSUE TITLE
predefined_metric_type is not configurable

### ISSUE THREAD

**Issue by pjfbashton** [terraform-aws-modules/terraform-aws-rds-aurora#67]
`target_tracking_scaling_policy_configuration` is [hardcoded](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L132-L135) to use `RDSReaderAverageCPUUtilization` for metric type.

``` 
target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "RDSReaderAverageCPUUtilization"
    }
```

It would be good to make it configurable. 
I have created PR to enable such configuration: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/66

**Comment by antonbabenko** [comment]
[v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.6.0) has been released with this feature.
