### ISSUE TITLE
Output is missing DB Instance IDs

### ISSUE THREAD

**Issue by vishnuhd** [terraform-aws-modules/terraform-aws-rds-aurora#82]
Currently, when Aurora Cluster is created, only Cluster ID is exposed in output.

We have a use case where we need instance IDs as well to setup CloudWatch Alarms on each instance.

It would be helpful if we can get the instance IDs as well in outputs.

Thanks.

**Comment by tomasbackman** [comment]
I created a PR for this

**Comment by bryantbiggs** [comment]
closed with #107
