### ISSUE TITLE
AWS Secrets Manager + Aurora RDS module

### ISSUE THREAD

**Issue by marcincuber** [terraform-aws-modules/terraform-aws-rds-aurora#90]
Hi,

I would like to make use of AWS Secrets Manager to rotate root credentials for the aurora db mysql. Could you advise how to do it using this module or maybe you have some useful example where this is being done?

**Comment by Saltcastle** [comment]
Hi marcincuber, 

i do not have exactly what you asked for, but i can show you my way of storing the aurora db master password with secrets manager with this aurora-module. (keep in mind, that it won't rotate. For that find more information at [Terraform-documentation](https://www.terraform.io/docs/providers/aws/r/secretsmanager_secret.html#rotation-configuration) or maybe another person can complete my answer.

Prerequisites: 
1. do not set password in module-call
2. ${module.label.id} is my way of forcing naming-convention throughout every resource. ([not obligatory](https://github.com/cloudposse/terraform-null-label))

```
### store db credentials in secrets manager

resource "aws_secretsmanager_secret" "db_master_password" {
  name = "${module.label.id}-db-master-password"
  recovery_window_in_days = 0

  tags = module.label.tags
}

resource "aws_secretsmanager_secret_version" "db_master_password" {
  secret_id      = aws_secretsmanager_secret.db_master_password.id
  secret_string  = local.master_password
  version_stages = ["AWSCURRENT"]
}

### retrieve secret 

data "aws_secretsmanager_secret" "db_master_password" {
  arn = aws_secretsmanager_secret.db_master_password.arn
}

data "aws_secretsmanager_secret_version" "db_master_password" {
  secret_id = data.aws_secretsmanager_secret.db_master_password.id
}
```
Feel free to correct any mistakes or mention improvements.

**Comment by anilsakr** [comment]
Here is the solution
https://blog.gruntwork.io/a-comprehensive-guide-to-managing-secrets-in-your-terraform-code-1d586955ace1
