### ISSUE TITLE
Ability to set the RDS Cluster certificate authority before March 5 Certificate expiration

### ISSUE THREAD

**Issue by juliovalcarcel** [terraform-aws-modules/terraform-aws-rds-aurora#91]
Once [this pull request](https://github.com/terraform-providers/terraform-provider-aws/pull/10954) is merged in the ability to pass `ca_cert_identifier` through this module will also be needed before the March deadline to update the certificate. 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by tjbaker** [comment]
This was merged a some time ago to the rds module and has been in 2 releases.  Can we get this working for the aurora module?

**Comment by acholt** [comment]
I have tested this against my own environments and everything is working as expected. Please let me know if there is anything I missed as part of the contributor's guidelines.

**Comment by juliovalcarcel** [comment]
@antonbabenko would you mind taking a look at this and the pull request

**Comment by bryantbiggs** [comment]
I believe this is resolved with #98
