### ISSUE TITLE
Make availability zone configurable for rds aurora

### ISSUE THREAD

**Issue by lwojtas** [terraform-aws-modules/terraform-aws-rds-aurora#92]
Please add another input variable availability_zones to aws rds cluster

```
resource "aws_rds_cluster" "default" {
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]
}
```

Thanks

**Comment by kozub** [comment]
I believe that it was removed intentionally. Please check https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/10 to get more details.

**Comment by antonbabenko** [comment]
Closing this one, according to what @kozub refers to.

**Comment by Vad1mo** [comment]
So what is the alternative is AZs are now removed how is it possible to select an AZ or doesn't it matter?

**Comment by antonbabenko** [comment]
You need to specify the DB subnet group and don't use the availability zone. See this, for example: https://github.com/hashicorp/terraform/issues/16724#issuecomment-400353356
