### ISSUE TITLE
Incorrect example for PostgreSQL Serverless 

### ISSUE THREAD

**Issue by a7i** [terraform-aws-modules/terraform-aws-rds-aurora#94]
The current Serverless example for PostgreSQL does not work. It is using Parameter Group `aurora5.6` which is for Serverless MySQL 5.6. Instead, it should be using `aurora-postgresql10` for PostgreSQL which can be found in [`AWS Aurora Serverless Documentation`](https://docs.aws.amazon.com/en_us/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.how-it-works.html)

I will be creating a PR and associate it with this Issue.

**Comment by antonbabenko** [comment]
Fixed in [v3.3.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v3.3.0) has been just released.
